/* tslint:disable:class-name */
import { ExifDate, ExifTime, ExifDateTime, ExifTimeZoneOffset } from "./DateTime"

// Autogenerated by "npm run mktags" by ExifTool 10.54 on Wed May 31 2017.
// 4181 unique tags were found in 6419 different digital imagery files.

// Comments by each tag include popularity (★★★ is > 70% of cameras, ☆☆☆ is rare),
// followed by a checkmark if the tag is used by recent, popular devices (like iPhones)
// An example value, JSON stringified, follows the popularity ratings.

export interface ExifToolTags {
  /** ★★★ ✔ "10.54" */
  ExifToolVersion: string
  /** ☆☆☆   "Invalid EXIF text encoding for UserComment" */
  Warning: string
}

export interface FileTags {
  /** ★★★ ✔ [8] */
  BitsPerSample: number[]
  /** ★★★ ✔ 3 */
  ColorComponents: number
  /** ☆☆☆   "LEAD Technologies Inc. V1.01" */
  Comment: string
  /** ☆☆☆ ✔ "d41d8cd98f00b204e9800998ecf8427e" */
  CurrentIPTCDigest: string
  /** ★★★ ✔ "/home/mrm/src/test-images/Acer" */
  Directory: string
  /** ★★★ ✔ "Baseline DCT, Huffman coding" */
  EncodingProcess: string
  /** ★★★ ✔ "Little-endian (Intel, II)" */
  ExifByteOrder: string
  /** ★★★ ✔ {"year":2017,"month":5,"day":31,"hour":9,"minute":19,"second":2,"tzoffsetMinute… */
  FileAccessDate: ExifDateTime
  /** ★★★ ✔ {"year":2017,"month":4,"day":21,"hour":16,"minute":32,"second":54,"tzoffsetMinu… */
  FileInodeChangeDate: ExifDateTime
  /** ★★★ ✔ {"year":2010,"month":6,"day":11,"hour":10,"minute":45,"second":6,"tzoffsetMinut… */
  FileModifyDate: ExifDateTime
  /** ★★★ ✔ "AcerCI-8330.jpg" */
  FileName: string
  /** ★★★ ✔ "rw-r--r--" */
  FilePermissions: string
  /** ★★★ ✔ "8.5 kB" */
  FileSize: string
  /** ★★★ ✔ "JPEG" */
  FileType: string
  /** ★★★ ✔ "jpg" */
  FileTypeExtension: string
  /** ★★★ ✔ 8 */
  ImageHeight: number
  /** ★★★ ✔ 8 */
  ImageWidth: number
  /** ★★★ ✔ "image/jpeg" */
  MIMEType: string
  /** ☆☆☆ ✔ "(Binary data 59046 bytes, use -b option to extract)" */
  PreviewImage: string
  /** ☆☆☆ ✔ "0100" */
  RAFVersion: string
  /** ★★★ ✔ "YCbCr4:2:0 (2 2)" */
  YCbCrSubSampling: string
}

export interface EXIFTags {
  /** ★☆☆ ✔ 2.6 */
  ApertureValue: number
  /** ☆☆☆ ✔ "@????@" */
  Artist: string
  /** ☆☆☆ ✔ 1 */
  BlackLevel1: number
  /** ☆☆☆ ✔ 4 */
  BlackLevel2: number
  /** ☆☆☆ ✔ 12 */
  BlackLevel3: number
  /** ☆☆☆ ✔ 128 */
  BlackLevelBlue: number
  /** ☆☆☆ ✔ 128 */
  BlackLevelGreen: number
  /** ☆☆☆ ✔ 128 */
  BlackLevelRed: number
  /** ☆☆☆ ✔ 2.812148481 */
  BrightnessValue: number
  /** ☆☆☆ ✔ "[Green,Red][Blue,Green]" */
  CFAPattern: string
  /** ☆☆☆ ✔ "0 1 1 2" */
  CFAPattern2: string
  /** ☆☆☆ ✔ "2 2" */
  CFARepeatPatternDim: string
  /** ☆☆☆ ✔ "[Green,Blue][Red,Green]" */
  CR2CFAPattern: string
  /** ☆☆☆ ✔ "22 -128 0 0 0 128 128 256 384 384 512 640 1152 1152 1152 1024 896 768 640 640 … */
  ChromaticAberrationCorrParams: string
  /** ★★★ ✔ "sRGB" */
  ColorSpace: string
  /** ★★★ ✔ "Y, Cb, Cr, -" */
  ComponentsConfiguration: string
  /** ★★☆ ✔ 2.045931133 */
  CompressedBitsPerPixel: number
  /** ★★★ ✔ "JPEG (old-style)" */
  Compression: string
  /** ★☆☆ ✔ "Normal" */
  Contrast: string
  /** ☆☆☆ ✔ "Copyrights 2009 Acer Incorporate" */
  Copyright: string
  /** ★★★ ✔ {"year":2005,"month":1,"day":27,"hour":19,"minute":48,"second":50,"millis":0} */
  CreateDate: ExifDateTime
  /** ★★☆ ✔ "Normal" */
  CustomRendered: string
  /** ★★★ ✔ {"year":2005,"month":1,"day":27,"hour":19,"minute":48,"second":50,"millis":0} */
  DateTimeOriginal: ExifDateTime
  /** ☆☆☆ ✔ "(Binary data 4 bytes, use -b option to extract)" */
  DeviceSettingDescription: string
  /** ★★☆ ✔ 1 */
  DigitalZoomRatio: number
  /** ☆☆☆ ✔ "11 32 4 -36 -83 -142 -208 -286 -363 -444 -521 -598 0 0 0 0 0" */
  DistortionCorrParams: string
  /** ★★★ ✔ 1704 */
  ExifImageHeight: number
  /** ★★★ ✔ 2272 */
  ExifImageWidth: number
  /** ★★★ ✔ "0220" */
  ExifVersion: string
  /** ★★☆ ✔ "+1.3" */
  ExposureCompensation: number
  /** ☆☆☆ ✔ 1 */
  ExposureIndex: number
  /** ★★☆ ✔ "Auto" */
  ExposureMode: string
  /** ★★☆ ✔ "Program AE" */
  ExposureProgram: string
  /** ★★★ ✔ "1/30" */
  ExposureTime: string
  /** ★★★ ✔ 2.8 */
  FNumber: number
  /** ★★☆ ✔ "Digital Camera" */
  FileSource: string
  /** ★★★ ✔ "Auto, Fired" */
  Flash: string
  /** ★★★ ✔ "0100" */
  FlashpixVersion: string
  /** ★★☆ ✔ "7.3 mm" */
  FocalLength: string
  /** ★☆☆ ✔ "51 mm" */
  FocalLengthIn35mmFormat: string
  /** ☆☆☆ ✔ "inches" */
  FocalPlaneResolutionUnit: string
  /** ☆☆☆ ✔ 1 */
  FocalPlaneXResolution: number
  /** ☆☆☆ ✔ 2 */
  FocalPlaneYResolution: number
  /** ☆☆☆ ✔ "0 m" */
  GPSAltitude: string
  /** ☆☆☆ ✔ "Below Sea Level" */
  GPSAltitudeRef: string
  /** ☆☆☆   1.2 */
  GPSDOP: number
  /** ☆☆☆ ✔ {"year":2002,"month":12,"day":8} */
  GPSDateStamp: ExifDate
  /** ☆☆☆ ✔ 274.8004158 */
  GPSDestBearing: number
  /** ☆☆☆ ✔ "True North" */
  GPSDestBearingRef: string
  /** ☆☆☆ ✔ "25 m" */
  GPSHPositioningError: string
  /** ☆☆☆ ✔ 264.3684211 */
  GPSImgDirection: number
  /** ☆☆☆ ✔ "True North" */
  GPSImgDirectionRef: string
  /** ☆☆☆ ✔ 59.94721111 */
  GPSLatitude: number
  /** ☆☆☆ ✔ "South" */
  GPSLatitudeRef: string
  /** ☆☆☆ ✔ 30.19316389 */
  GPSLongitude: number
  /** ☆☆☆ ✔ "West" */
  GPSLongitudeRef: string
  /** ☆☆☆   "WGS84" */
  GPSMapDatum: string
  /** ☆☆☆   "3-Dimensional Measurement" */
  GPSMeasureMode: string
  /** ☆☆☆   "GPS\u0000" */
  GPSProcessingMethod: string
  /** ☆☆☆ ✔ 0.49 */
  GPSSpeed: number
  /** ☆☆☆ ✔ "km/h" */
  GPSSpeedRef: string
  /** ☆☆☆ ✔ "Measurement Active" */
  GPSStatus: string
  /** ☆☆☆ ✔ {"hour":12,"minute":0,"second":0,"tzoffsetMinutes":0,"millis":0} */
  GPSTimeStamp: ExifTime
  /** ☆☆☆ ✔ "2.0.0.0" */
  GPSVersionID: string
  /** ☆☆☆ ✔ "None" */
  GainControl: string
  /** ☆☆☆   2.2 */
  Gamma: number
  /** ☆☆☆ ✔ 1 */
  HighISOMultiplierBlue: number
  /** ☆☆☆ ✔ 1 */
  HighISOMultiplierGreen: number
  /** ☆☆☆ ✔ 1 */
  HighISOMultiplierRed: number
  /** ☆☆☆ ✔ "iPhone (iPhone OS 8.1.2)" */
  HostComputer: string
  /** ★★☆ ✔ 100 */
  ISO: number
  /** ★☆☆ ✔ "Digital StillCamera" */
  ImageDescription: string
  /** ☆☆☆ ✔ "b6cbe2dd40d4d9de189b18448524a417" */
  ImageUniqueID: string
  /** ★★★ ✔ "R98 - DCF basic file (sRGB)" */
  InteropIndex: string
  /** ★★★ ✔ "0100" */
  InteropVersion: string
  /** ☆☆☆ ✔ "(Binary data 1114996 bytes, use -b option to extract)" */
  JpgFromRaw: string
  /** ☆☆☆ ✔ 1114996 */
  JpgFromRawLength: number
  /** ☆☆☆ ✔ 786432 */
  JpgFromRawStart: number
  /** ☆☆☆ ✔ "3.3mm f/2.4" */
  LensInfo: string
  /** ☆☆☆ ✔ "Apple" */
  LensMake: string
  /** ☆☆☆ ✔ "iPad Air 2 back camera 3.3mm f/2.4" */
  LensModel: string
  /** ☆☆☆ ✔ "00001027b4" */
  LensSerialNumber: string
  /** ☆☆☆ ✔ "11 0 32 144 352 640 1040 1536 2144 2848 3600 4400 0 0 0 0 0" */
  LightFalloffParams: string
  /** ★★☆ ✔ "Flash" */
  LightSource: string
  /** ☆☆☆ ✔ 2626 */
  LinearityLimitBlue: number
  /** ☆☆☆ ✔ 2626 */
  LinearityLimitGreen: number
  /** ☆☆☆ ✔ 2626 */
  LinearityLimitRed: number
  /** ★★★ ✔ "acer" */
  Make: string
  /** ☆☆☆   "(Binary data 2560 bytes, use -b option to extract)" */
  MakerNoteUnknownText: string
  /** ★★☆ ✔ 2.8 */
  MaxApertureValue: number
  /** ★★★ ✔ "Center-weighted average" */
  MeteringMode: string
  /** ★★★ ✔ "CI-8330" */
  Model: string
  /** ★★★ ✔ {"year":2005,"month":1,"day":27,"hour":19,"minute":48,"second":50,"millis":0} */
  ModifyDate: ExifDateTime
  /** ☆☆☆ ✔ 4196 */
  OffsetSchema: number
  /** ★★★ ✔ "Horizontal (normal)" */
  Orientation: string
  /** ☆☆☆ ✔ "(Binary data 2400 bytes, use -b option to extract)" */
  OtherImage: string
  /** ☆☆☆ ✔ 2400 */
  OtherImageLength: number
  /** ☆☆☆ ✔ 1274 */
  OtherImageStart: number
  /** ☆☆☆ ✔ "Jonathan Crowther" */
  OwnerName: string
  /** ☆☆☆ ✔ "(Binary data 2060 bytes, use -b option to extract)" */
  Padding: string
  /** ☆☆☆ ✔ "0330" */
  PanasonicRawVersion: string
  /** ☆☆☆ ✔ "YCbCr" */
  PhotometricInterpretation: string
  /** ☆☆☆ ✔ "Chunky" */
  PlanarConfiguration: string
  /** ☆☆☆ ✔ {"year":2015,"month":6,"day":2,"hour":9,"minute":56,"second":1,"millis":0} */
  PreviewDateTime: ExifDateTime
  /** ☆☆☆ ✔ 1794122 */
  PreviewImageLength: number
  /** ☆☆☆ ✔ 70744 */
  PreviewImageStart: number
  /** ☆☆☆   "0.64 0.33 0.3 0.6 0.15 0.06" */
  PrimaryChromaticities: string
  /** ☆☆☆ ✔ "ACD Systems Digital Imaging" */
  ProcessingSoftware: string
  /** ☆☆☆   1 */
  Rating: number
  /** ☆☆☆ ✔ 928768 */
  RawDataOffset: number
  /** ☆☆☆ ✔ "2 1728 1888" */
  RawImageSegmentation: string
  /** ☆☆☆ ✔ 100 */
  RecommendedExposureIndex: number
  /** ☆☆☆ ✔ "0 255 128 255 128 255" */
  ReferenceBlackWhite: string
  /** ☆☆☆ ✔ 1080 */
  RelatedImageHeight: number
  /** ☆☆☆ ✔ 1920 */
  RelatedImageWidth: number
  /** ☆☆☆   "RelatedSound" */
  RelatedSoundFile: string
  /** ★★★ ✔ "inches" */
  ResolutionUnit: string
  /** ☆☆☆ ✔ 60 */
  RowsPerStrip: number
  /** ☆☆☆ ✔ 1 */
  SRawType: number
  /** ☆☆☆ ✔ 3 */
  SamplesPerPixel: number
  /** ★☆☆ ✔ "Normal" */
  Saturation: string
  /** ★★☆ ✔ "Standard" */
  SceneCaptureType: string
  /** ★☆☆ ✔ "Directly photographed" */
  SceneType: string
  /** ★☆☆ ✔ "One-chip color area" */
  SensingMethod: string
  /** ☆☆☆ ✔ "Recommended Exposure Index" */
  SensitivityType: string
  /** ☆☆☆ ✔ 3432 */
  SensorBottomBorder: number
  /** ☆☆☆ ✔ 3440 */
  SensorHeight: number
  /** ☆☆☆ ✔ 8 */
  SensorLeftBorder: number
  /** ☆☆☆ ✔ 3432 */
  SensorRightBorder: number
  /** ☆☆☆ ✔ 8 */
  SensorTopBorder: number
  /** ☆☆☆ ✔ 3472 */
  SensorWidth: number
  /** ☆☆☆ ✔ "033021006685" */
  SerialNumber: string
  /** ★☆☆ ✔ "Normal" */
  Sharpness: string
  /** ★☆☆ ✔ 0.7 */
  ShutterSpeedValue: string
  /** ★★☆ ✔ "1.0004.2A" */
  Software: string
  /** ☆☆☆ ✔ "Sony Compressed RAW" */
  SonyRawFileType: string
  /** ☆☆☆ ✔ 9600 */
  StripByteCounts: number
  /** ☆☆☆ ✔ 796 */
  StripOffsets: number
  /** ☆☆☆ ✔ "1\u0000" */
  SubSecTime: number
  /** ☆☆☆ ✔ 118 */
  SubSecTimeDigitized: number
  /** ☆☆☆ ✔ 118 */
  SubSecTimeOriginal: number
  /** ☆☆☆ ✔ "Full-resolution Image" */
  SubfileType: string
  /** ☆☆☆ ✔ "778 886 484 484" */
  SubjectArea: string
  /** ☆☆☆ ✔ "10 m" */
  SubjectDistance: string
  /** ☆☆☆ ✔ "Unknown" */
  SubjectDistanceRange: string
  /** ★★★ ✔ "(Binary data 7536 bytes, use -b option to extract)" */
  ThumbnailImage: string
  /** ★★★ ✔ 7536 */
  ThumbnailLength: number
  /** ★★★ ✔ 968 */
  ThumbnailOffset: number
  /** ☆☆☆ ✔ "(Binary data 57816 bytes, use -b option to extract)" */
  ThumbnailTIFF: string
  /** ★☆☆ ✔ "Edited with Nokia Editor Application" */
  UserComment: string
  /** ☆☆☆ ✔ 525 */
  WBBlueLevel: number
  /** ☆☆☆ ✔ 265 */
  WBGreenLevel: number
  /** ☆☆☆ ✔ 527 */
  WBRedLevel: number
  /** ★★☆ ✔ "Auto" */
  WhiteBalance: string
  /** ☆☆☆   "0.3127 0.329" */
  WhitePoint: string
  /** ☆☆☆ ✔ "Hugues CREPIN" */
  XPAuthor: string
  /** ★★★ ✔ 180 */
  XResolution: number
  /** ☆☆☆   "0.299 0.587 0.114" */
  YCbCrCoefficients: string
  /** ★★★ ✔ "Co-sited" */
  YCbCrPositioning: string
  /** ★★★ ✔ 180 */
  YResolution: number
}

export interface CompositeTags {
  /** ☆☆☆ ✔ "Off" */
  AdvancedSceneMode: string
  /** ★★★ ✔ 2.8 */
  Aperture: number
  /** ☆☆☆ ✔ "Off" */
  AutoFocus: string
  /** ☆☆☆ ✔ 1.557409 */
  BlueBalance: number
  /** ★☆☆ ✔ "0.005 mm" */
  CircleOfConfusion: string
  /** ☆☆☆ ✔ undefined */
  ConditionalFEC: number
  /** ☆☆☆ ✔ "0.27 m (0.88 - 1.16 m)" */
  DOF: string
  /** ☆☆☆   {"year":2005,"month":11,"day":19} */
  DateCreated: ExifDate
  /** ☆☆☆ ✔ {"year":2014,"month":10,"day":31,"hour":13,"minute":15,"second":35,"millis":0} */
  DateTimeCreated: ExifDateTime
  /** ☆☆☆ ✔ {"year":2016,"month":8,"day":12,"hour":13,"minute":28,"second":50,"millis":0} */
  DigitalCreationDateTime: ExifDateTime
  /** ☆☆☆ ✔ "Single-frame Shooting" */
  DriveMode: string
  /** ☆☆☆ ✔ "Not attached" */
  ExtenderStatus: string
  /** ★☆☆ ✔ "53.8 deg" */
  FOV: string
  /** ☆☆☆ ✔ "100-0285" */
  FileNumber: string
  /** ☆☆☆ ✔ "Built-In Flash" */
  FlashType: string
  /** ★★☆ ✔ "7.3 mm" */
  FocalLength35efl: string
  /** ☆☆☆ ✔ "6.10 m" */
  FocusDistance2: string
  /** ☆☆☆ ✔ {"year":2002,"month":12,"day":8,"hour":12,"minute":0,"second":0,"tzoffsetMinute… */
  GPSDateTime: ExifDateTime
  /** ☆☆☆ ✔ "0.00000000 N, 0.00000000 E" */
  GPSPosition: string
  /** ★☆☆ ✔ "2.28 m" */
  HyperfocalDistance: string
  /** ★★★ ✔ "8x8" */
  ImageSize: string
  /** ☆☆☆ ✔ "4.8 - 57.6 mm" */
  Lens: string
  /** ☆☆☆ ✔ "4.8 - 57.6 mm (35 mm equivalent: 41.9 - 503.2 mm)" */
  Lens35efl: string
  /** ☆☆☆ ✔ "Unknown 4-57mm" */
  LensID: string
  /** ☆☆☆ ✔ "200mm f/2 G VR" */
  LensSpec: string
  /** ★★☆ ✔ 7.9 */
  LightValue: number
  /** ★★★ ✔ 0.000064 */
  Megapixels: number
  /** ☆☆☆   "10.4 um" */
  PeakSpectralSensitivity: string
  /** ☆☆☆ ✔ "1536x1024" */
  PreviewImageSize: string
  /** ☆☆☆ ✔ 2.294406 */
  RedBalance: number
  /** ☆☆☆ ✔ "Off" */
  RedEyeReduction: string
  /** ☆☆☆ ✔ "4:56:35" */
  RunTimeSincePowerUp: ExifTime
  /** ★☆☆ ✔ 6.6 */
  ScaleFactor35efl: number
  /** ☆☆☆ ✔ "Program AE" */
  ShootingMode: string
  /** ☆☆☆ ✔ "1st-curtain sync" */
  ShutterCurtainHack: string
  /** ★★★ ✔ "1/30" */
  ShutterSpeed: string
  /** ☆☆☆ ✔ {"year":2014,"month":10,"day":30,"hour":15,"minute":30,"second":51,"millis":118… */
  SubSecCreateDate: ExifDateTime
  /** ☆☆☆ ✔ {"year":2014,"month":10,"day":30,"hour":15,"minute":30,"second":51,"millis":118… */
  SubSecDateTimeOriginal: ExifDateTime
  /** ☆☆☆ ✔ {"year":2009,"month":2,"day":21,"hour":16,"minute":18,"second":0,"millis":100} */
  SubSecModifyDate: ExifDateTime
  /** ☆☆☆ ✔ "2338 1019 1019 1587" */
  WB_RGGBLevels: string
}

export interface MakerNotesTags {
  /** ☆☆☆   8 */
  AEAperture: number
  /** ☆☆☆ ✔ "On" */
  AEBAutoCancel: string
  /** ☆☆☆ ✔ "+0.25" */
  AEBBracketValue: number
  /** ☆☆☆ ✔ "0,-,+" */
  AEBSequence: string
  /** ☆☆☆ ✔ "0,-,+/Enabled" */
  AEBSequenceAutoCancel: string
  /** ☆☆☆ ✔ "7 shots" */
  AEBShotCount: string
  /** ☆☆☆ ✔ "AE Bracketing Disabled" */
  AEBracketingSteps: string
  /** ☆☆☆   "1/744" */
  AEExposureTime: string
  /** ☆☆☆ ✔ "Off" */
  AELock: string
  /** ☆☆☆ ✔ "AE/AF Lock" */
  AELockButton: string
  /** ☆☆☆ ✔ "None" */
  AELockButtonPlusDials: string
  /** ☆☆☆   5.7 */
  AEMaxAperture: number
  /** ☆☆☆   5.7 */
  AEMaxAperture2: number
  /** ☆☆☆   "15.0 14.9 14.9 14.8 15.1 14.8 15.4 15.0 15.2 14.8 15.0 15.0 14.8 14.8 14.0 14.… */
  AEMeteringSegments: string
  /** ☆☆☆ ✔ "Enable; 0; 8; 0" */
  AEMicroadjustment: string
  /** ☆☆☆   38 */
  AEMinAperture: number
  /** ☆☆☆   "1/3862" */
  AEMinExposureTime: string
  /** ☆☆☆ ✔ "Normal AE" */
  AESetting: string
  /** ☆☆☆   200 */
  AE_ISO: number
  /** ☆☆☆ ✔ "Shutter/AF-On" */
  AFActivation: string
  /** ☆☆☆ ✔ 2 */
  AFAperture: number
  /** ☆☆☆ ✔ 42 */
  AFAreaHeight: number
  /** ☆☆☆ ✔ "37 37 37 37 37 37 37 37 37" */
  AFAreaHeights: string
  /** ☆☆☆ ✔ "Auto" */
  AFAreaMode: string
  /** ☆☆☆ ✔ "Wide" */
  AFAreaModeSetting: string
  /** ☆☆☆ ✔ "AF area selection button" */
  AFAreaSelectMethod: string
  /** ☆☆☆ ✔ "M-Fn Button" */
  AFAreaSelectionMethod: string
  /** ☆☆☆ ✔ 369 */
  AFAreaWidth: number
  /** ☆☆☆ ✔ "53 53 53 53 53 53 53 53 53" */
  AFAreaWidths: string
  /** ☆☆☆ ✔ "-54 0 53 -54 0 53 -54 0 53" */
  AFAreaXPositions: string
  /** ☆☆☆ ✔ "-38 -38 -38 0 0 0 38 38 38" */
  AFAreaYPositions: string
  /** ☆☆☆ ✔ "none" */
  AFAreas: string
  /** ☆☆☆ ✔ "Emits/Fires" */
  AFAssist: string
  /** ☆☆☆ ✔ "Emits" */
  AFAssistBeam: string
  /** ☆☆☆ ✔ "Disabled and Not Required" */
  AFAssistLamp: string
  /** ☆☆☆ ✔ "Case 1" */
  AFConfigTool: string
  /** ☆☆☆   19 */
  AFDefocus: number
  /** ☆☆☆ ✔ "Off" */
  AFFineTune: string
  /** ☆☆☆ ✔ "0 0 0" */
  AFFineTuneAdj: string
  /** ☆☆☆ ✔ "n/a" */
  AFFineTuneIndex: string
  /** ☆☆☆   "Off" */
  AFIlluminator: string
  /** ☆☆☆ ✔ 240 */
  AFImageHeight: number
  /** ☆☆☆ ✔ 320 */
  AFImageWidth: number
  /** ☆☆☆ ✔ "0100" */
  AFInfo2Version: string
  /** ☆☆☆   "0 ms" */
  AFIntegrationTime: string
  /** ☆☆☆ ✔ "Disable" */
  AFMicroAdjMode: string
  /** ☆☆☆ ✔ undefined */
  AFMicroAdjValue: number
  /** ☆☆☆ ✔ "Disable; 0; 0; 0; 0" */
  AFMicroadjustment: string
  /** ☆☆☆ ✔ "Spot" */
  AFMode: string
  /** ☆☆☆ ✔ "No Restrictions" */
  AFModeRestrictions: string
  /** ☆☆☆ ✔ "Disable" */
  AFOnAELockButtonSwitch: string
  /** ☆☆☆ ✔ "AF On" */
  AFOnButton: string
  /** ☆☆☆ ✔ "Auto AF point selection" */
  AFPoint: string
  /** ☆☆☆ ✔ "Single AF point" */
  AFPointActivationArea: string
  /** ☆☆☆ ✔ "Disable" */
  AFPointAreaExpansion: string
  /** ☆☆☆ ✔ "Control-direct:disable/Main:enable" */
  AFPointAutoSelection: string
  /** ☆☆☆ ✔ "Normal" */
  AFPointBrightness: string
  /** ☆☆☆ ✔ "Selected (constant)" */
  AFPointDisplayDuringFocus: string
  /** ☆☆☆ ✔ "On" */
  AFPointIllumination: string
  /** ☆☆☆ ✔ "n/a" */
  AFPointPosition: string
  /** ☆☆☆ ✔ "Auto" */
  AFPointSelected: string
  /** ☆☆☆ ✔ "H=AF+Main/V=AF+Command" */
  AFPointSelection: string
  /** ☆☆☆ ✔ "45/Center AF point" */
  AFPointSpotMetering: string
  /** ☆☆☆ ✔ "None" */
  AFPointsInFocus: string
  /** ☆☆☆ ✔ "Auto (B6,B7,C6,C7,C8,D6,D7,D8)" */
  AFPointsInFocus1D: string
  /** ☆☆☆ ✔ "0,1,2,3,4,5,6" */
  AFPointsSelected: number
  /** ☆☆☆ ✔ "Center, Upper-right, Right, Lower-right, Upper-left, Far Left, Lower-middle, N… */
  AFPointsUsed: string
  /** ☆☆☆   27 */
  AFPredictor: number
  /** ☆☆☆   "Standard" */
  AFResponse: string
  /** ☆☆☆ ✔ "Not Ready" */
  AFSearch: string
  /** ☆☆☆   "Front Focus (-125)" */
  AFStatusActiveSensor: string
  /** ☆☆☆ ✔ "n/a" */
  AFZoneSelected: string
  /** ☆☆☆ ✔ "Shooting not possible without focus" */
  AIServoContinuousShooting: string
  /** ☆☆☆ ✔ "Focus Priority" */
  AIServoFirstImage: string
  /** ☆☆☆ ✔ "Equal priority" */
  AIServoFirstImagePriority: string
  /** ☆☆☆ ✔ "1: AF, 2: Tracking" */
  AIServoImagePriority: string
  /** ☆☆☆ ✔ "Focus Priority" */
  AIServoSecondImage: string
  /** ☆☆☆ ✔ "Equal priority" */
  AIServoSecondImagePriority: string
  /** ☆☆☆ ✔ "Main focus point priority" */
  AIServoTrackingMethod: string
  /** ☆☆☆ ✔ "Standard" */
  AIServoTrackingSensitivity: string
  /** ☆☆☆ ✔ "-0.9905017551 0.01082754704 0.02208212305" */
  AccelerationVector: string
  /** ☆☆☆ ✔ 4 */
  AccelerometerX: number
  /** ☆☆☆ ✔ 58 */
  AccelerometerY: number
  /** ☆☆☆ ✔ 270 */
  AccelerometerZ: number
  /** ☆☆☆ ✔ "0000000" */
  AccessorySerialNumber: string
  /** ☆☆☆ ✔ "NO-ACCESSORY" */
  AccessoryType: string
  /** ☆☆☆ ✔ "Off" */
  AddAspectRatioInfo: string
  /** ☆☆☆ ✔ "Off" */
  AddOriginalDecisionData: string
  /** ☆☆☆ ✔ 1 */
  AdvancedSceneType: number
  /** ☆☆☆ ✔ "Standard" */
  AmbienceSelection: string
  /** ☆☆☆ ✔ "19 C" */
  AmbientTemperature: string
  /** ☆☆☆ ✔ "Off" */
  ApertureLock: string
  /** ☆☆☆ ✔ "Disable; Closed 91; Open 1" */
  ApertureRange: string
  /** ☆☆☆ ✔ "Enable; 1; 2; 1; 128; 48; 0; 1" */
  ApplyShootingMeteringMode: string
  /** ☆☆☆ ✔ "Off; 0; 0; 0" */
  ArtFilter: string
  /** ☆☆☆ ✔ "Off; 0; 0; Partial Color 0; No Effect; 0; No Color Filter; 0; 0; 0; 0; 0; 0; 0… */
  ArtFilterEffect: string
  /** ☆☆☆ ✔ "0 0 4607 3455" */
  AspectFrame: string
  /** ☆☆☆ ✔ "3:2" */
  AspectRatio: string
  /** ☆☆☆ ✔ "Auto Bracketing" */
  AssignBktButton: string
  /** ☆☆☆ ✔ "None" */
  AssignMovieRecordButton: string
  /** ☆☆☆ ✔ "None" */
  AssignRemoteFnButton: string
  /** ☆☆☆ ✔ "No" */
  Audio: string
  /** ☆☆☆ ✔ "On-Shot AF only" */
  AutoAFPointColorTracking: string
  /** ☆☆☆ ✔ "Flash/Speed" */
  AutoBracketModeM: string
  /** ☆☆☆ ✔ "0,-,+" */
  AutoBracketOrder: string
  /** ☆☆☆ ✔ "AE & Flash" */
  AutoBracketSet: string
  /** ☆☆☆ ✔ "Off" */
  AutoBracketing: string
  /** ☆☆☆ ✔ "On" */
  AutoDistortionControl: string
  /** ☆☆☆ ✔ "200%" */
  AutoDynamicRange: string
  /** ☆☆☆ ✔ "Off" */
  AutoExposureBracketing: string
  /** ☆☆☆ ✔ "Off" */
  AutoISO: number
  /** ☆☆☆ ✔ "Enable" */
  AutoLightingOptimizer: string
  /** ☆☆☆ ✔ "No" */
  AutoPortraitFramed: string
  /** ☆☆☆ ✔ "None" */
  AutoRotate: string
  /** ☆☆☆   "Off" */
  AuxiliaryLens: string
  /** ☆☆☆ ✔ "Disable" */
  AvSettingWithoutLens: string
  /** ☆☆☆ ✔ "1024 1024 1024 1024" */
  AverageBlackLevel: string
  /** ☆☆☆   "Off" */
  BWMode: string
  /** ☆☆☆ ✔ "(not set)" */
  BabyAge: string
  /** ☆☆☆ ✔ "\u0005" */
  BabyName: string
  /** ☆☆☆ ✔ 65 */
  BaseISO: number
  /** ☆☆☆ ✔ "35%" */
  BatteryLevel: string
  /** ☆☆☆ ✔ "MB-D12 First" */
  BatteryOrder: string
  /** ☆☆☆ ✔ "28.3 C" */
  BatteryTemperature: string
  /** ☆☆☆ ✔ "Off" */
  Beep: string
  /** ☆☆☆ ✔ "600 600 600 600" */
  BlackLevel: string
  /** ☆☆☆ ✔ 2209 */
  BlackMaskBottomBorder: number
  /** ☆☆☆ ✔ 14 */
  BlackMaskLeftBorder: number
  /** ☆☆☆ ✔ 55 */
  BlackMaskRightBorder: number
  /** ☆☆☆ ✔ 162 */
  BlackMaskTopBorder: number
  /** ☆☆☆   "128 128 128 128" */
  BlackPoint: string
  /** ☆☆☆ ✔ "None" */
  BlurWarning: string
  /** ☆☆☆   "Full" */
  BodyBatteryState: string
  /** ☆☆☆ ✔ 1 */
  BodyFirmwareVersion: number
  /** ☆☆☆ ✔ "Off" */
  BracketMode: string
  /** ☆☆☆ ✔ "No Bracket" */
  BracketSettings: string
  /** ☆☆☆ ✔ "n/a" */
  BracketShotNumber: number
  /** ☆☆☆ ✔ 12 */
  BracketValue: number
  /** ☆☆☆ ✔ "Normal" */
  Brightness: number
  /** ☆☆☆ ✔ undefined */
  BulbDuration: number
  /** ☆☆☆ ✔ "Off" */
  BurstMode: string
  /** ☆☆☆ ✔ 3 */
  BurstSpeed: number
  /** ☆☆☆ ✔ "460727F2-20CF-4031-957B-7E04D567DF1F" */
  BurstUUID: string
  /** ☆☆☆ ✔ "Normal (enable)" */
  ButtonFunctionControlOff: string
  /** ☆☆☆ ✔ "9 fps" */
  CHModeShootingSpeed: string
  /** ☆☆☆ ✔ "3 fps" */
  CLModeShootingSpeed: string
  /** ☆☆☆   "1.00.00.00" */
  CPUFirmwareVersion: string
  /** ☆☆☆   "CPU1 1.02   CPU2 1.04, CPU3 1.00" */
  CPUVersions: string
  /** ☆☆☆ ✔ "ACER" */
  CameraID: string
  /** ☆☆☆ ✔ "Auto" */
  CameraISO: string
  /** ☆☆☆ ✔ "Horizontal (normal)" */
  CameraOrientation: string
  /** ☆☆☆   "(Binary data 5500 bytes, use -b option to extract)" */
  CameraParameters: string
  /** ☆☆☆ ✔ "Standard" */
  CameraPictureStyle: string
  /** ☆☆☆ ✔ "0100" */
  CameraSettingsVersion: string
  /** ☆☆☆ ✔ "26 C" */
  CameraTemperature: string
  /** ☆☆☆ ✔ "Unknown (CE5330)" */
  CameraType: string
  /** ☆☆☆ ✔ "E-M10MarkII" */
  CameraType2: string
  /** ☆☆☆ ✔ "Program AE" */
  CanonExposureMode: string
  /** ☆☆☆ ✔ "Firmware Version 1.0" */
  CanonFirmwareVersion: string
  /** ☆☆☆ ✔ "Off" */
  CanonFlashMode: string
  /** ☆☆☆ ✔ 1840 */
  CanonImageHeight: number
  /** ☆☆☆ ✔ "Widescreen" */
  CanonImageSize: string
  /** ☆☆☆ ✔ "IMG:iVIS HF10 JPEG" */
  CanonImageType: string
  /** ☆☆☆ ✔ 3264 */
  CanonImageWidth: number
  /** ☆☆☆ ✔ "HF10" */
  CanonModelID: string
  /** ☆☆☆ ✔ "(none)" */
  Categories: string
  /** ☆☆☆ ✔ "12 mm" */
  CenterWeightedAreaSize: string
  /** ☆☆☆ ✔ "Off" */
  ChromaticAberrationCorr: string
  /** ☆☆☆ ✔ "On" */
  ChromaticAberrationSetting: string
  /** ☆☆☆ ✔ "TEDDINGTON" */
  City: string
  /** ☆☆☆ ✔ "---" */
  City2: string
  /** ☆☆☆ ✔ 4 */
  Clarity: number
  /** ☆☆☆ ✔ "Off" */
  ClearRetouch: string
  /** ☆☆☆ ✔ "undef" */
  ClearRetouchValue: string
  /** ☆☆☆   "Off" */
  ColorAdjustmentMode: string
  /** ☆☆☆ ✔ "0224" */
  ColorBalanceVersion: string
  /** ☆☆☆ ✔ -1 */
  ColorCompensationFilter: number
  /** ☆☆☆ ✔ "Color 0; 0; 29; Strength 0; -4; 3" */
  ColorCreatorEffect: string
  /** ☆☆☆ ✔ "5 (450D/1000D)" */
  ColorDataVersion: string
  /** ☆☆☆ ✔ "Off" */
  ColorEffect: string
  /** ☆☆☆ ✔ "Mode1" */
  ColorHue: string
  /** ☆☆☆ ✔ "432 -148 -28 -68 384 -60 14 -132 374" */
  ColorMatrix: string
  /** ☆☆☆ ✔ "Off" */
  ColorMode: string
  /** ☆☆☆ ✔ 4551 */
  ColorTempAsShot: number
  /** ☆☆☆ ✔ 4551 */
  ColorTempAuto: number
  /** ☆☆☆ ✔ 6000 */
  ColorTempCloudy: number
  /** ☆☆☆ ✔ 5210 */
  ColorTempCustom: number
  /** ☆☆☆ ✔ 5200 */
  ColorTempDaylight: number
  /** ☆☆☆ ✔ 6456 */
  ColorTempFlash: number
  /** ☆☆☆ ✔ 3901 */
  ColorTempFluorescent: number
  /** ☆☆☆ ✔ 5190 */
  ColorTempKelvin: number
  /** ☆☆☆ ✔ 4276 */
  ColorTempMeasured: number
  /** ☆☆☆ ✔ 4076 */
  ColorTempPC1: number
  /** ☆☆☆ ✔ 4076 */
  ColorTempPC2: number
  /** ☆☆☆ ✔ 4076 */
  ColorTempPC3: number
  /** ☆☆☆ ✔ 7000 */
  ColorTempShade: number
  /** ☆☆☆ ✔ 3200 */
  ColorTempTungsten: number
  /** ☆☆☆ ✔ 5200 */
  ColorTemperature: number
  /** ☆☆☆ ✔ "Normal" */
  ColorTone: string
  /** ☆☆☆ ✔ undefined */
  ColorToneFaithful: number
  /** ☆☆☆ ✔ undefined */
  ColorToneLandscape: number
  /** ☆☆☆ ✔ undefined */
  ColorToneNeutral: number
  /** ☆☆☆ ✔ undefined */
  ColorTonePortrait: number
  /** ☆☆☆ ✔ undefined */
  ColorToneStandard: number
  /** ☆☆☆ ✔ undefined */
  ColorToneUserDef1: number
  /** ☆☆☆ ✔ 1 */
  ColorToneUserDef2: number
  /** ☆☆☆ ✔ undefined */
  ColorToneUserDef3: number
  /** ☆☆☆ ✔ "Sub-command Dial" */
  CommandDialsApertureSetting: string
  /** ☆☆☆ ✔ "Autofocus Off, Exposure Off" */
  CommandDialsChangeMainSub: string
  /** ☆☆☆ ✔ "Off" */
  CommandDialsMenuAndPlayback: string
  /** ☆☆☆ ✔ "No" */
  CommandDialsReverseRotation: string
  /** ☆☆☆ ✔ 4 */
  CompressionFactor: number
  /** ☆☆☆ ✔ "Single" */
  ContinuousDrive: string
  /** ☆☆☆ ✔ "Disable; Hi 10; Lo 3" */
  ContinuousShootingSpeed: string
  /** ☆☆☆ ✔ "Disable; 99 shots" */
  ContinuousShotLimit: string
  /** ☆☆☆ ✔ "(Binary data 578 bytes, use -b option to extract)" */
  ContrastCurve: string
  /** ☆☆☆ ✔ "Off" */
  ContrastDetectAF: string
  /** ☆☆☆ ✔ "No" */
  ContrastDetectAFInFocus: string
  /** ☆☆☆ ✔ undefined */
  ContrastFaithful: number
  /** ☆☆☆ ✔ undefined */
  ContrastLandscape: number
  /** ☆☆☆ ✔ "Unknown (0xe)" */
  ContrastMode: string
  /** ☆☆☆ ✔ undefined */
  ContrastMonochrome: number
  /** ☆☆☆ ✔ undefined */
  ContrastNeutral: number
  /** ☆☆☆ ✔ undefined */
  ContrastPortrait: number
  /** ☆☆☆ ✔ "0 (min -5, max 5)" */
  ContrastSetting: string
  /** ☆☆☆ ✔ 1 */
  ContrastStandard: number
  /** ☆☆☆ ✔ 3 */
  ContrastUserDef1: number
  /** ☆☆☆ ✔ undefined */
  ContrastUserDef2: number
  /** ☆☆☆ ✔ undefined */
  ContrastUserDef3: number
  /** ☆☆☆ ✔ "n/a" */
  ControlMode: string
  /** ☆☆☆ ✔ "Off" */
  ConversionLens: string
  /** ☆☆☆   2176 */
  CoringFilter: number
  /** ☆☆☆ ✔ "ENGLAND" */
  Country: string
  /** ☆☆☆ ✔ "Standard" */
  CreativeStyle: string
  /** ☆☆☆ ✔ 14 */
  CropBottomMargin: number
  /** ☆☆☆ ✔ 3456 */
  CropHeight: number
  /** ☆☆☆ ✔ "Off (4320x2868 cropped to 4320x2868 at pixel 0,0)" */
  CropHiSpeed: string
  /** ☆☆☆ ✔ "8 0" */
  CropLeft: string
  /** ☆☆☆ ✔ 22 */
  CropLeftMargin: number
  /** ☆☆☆ ✔ 20 */
  CropRightMargin: number
  /** ☆☆☆ ✔ "8 0" */
  CropTop: string
  /** ☆☆☆ ✔ 14 */
  CropTopMargin: number
  /** ☆☆☆ ✔ 4608 */
  CropWidth: number
  /** ☆☆☆ ✔ 3456 */
  CroppedImageHeight: number
  /** ☆☆☆ ✔ 304 */
  CroppedImageLeft: number
  /** ☆☆☆ ✔ undefined */
  CroppedImageTop: number
  /** ☆☆☆ ✔ 5184 */
  CroppedImageWidth: number
  /** ☆☆☆ ✔ "0 0 1 0 0 1" */
  CustomControls: string
  /** ☆☆☆ ✔ "P-STUDIO" */
  CustomPictureStyleFileName: string
  /** ☆☆☆ ✔ "0 (min -5, max 5)" */
  CustomSaturation: string
  /** ☆☆☆ ✔ "No" */
  CustomSettingsAllDefault: string
  /** ☆☆☆ ✔ "A" */
  CustomSettingsBank: string
  /** ☆☆☆ ✔ 6475 */
  CustomSettingsOffset: number
  /** ☆☆☆ ✔ "Matrix" */
  D810MeteringMode: string
  /** ☆☆☆   "10.01.00.00" */
  DSPFirmwareVersion: string
  /** ☆☆☆ ✔ "(Binary data 122 bytes, use -b option to extract)" */
  DataDump: string
  /** ☆☆☆   8192 */
  DataScaling: number
  /** ☆☆☆   {"year":2006,"month":2,"day":11} */
  Date: ExifDate
  /** ☆☆☆ ✔ "Y/M/D" */
  DateDisplayFormat: string
  /** ☆☆☆ ✔ "Off" */
  DateStampMode: string
  /** ☆☆☆   "Off" */
  DateTimeStamp: string
  /** ☆☆☆ ✔ "0000:00:00 00:00:00" */
  DateTimeUTC: ExifDateTime
  /** ☆☆☆ ✔ "Off" */
  DaylightSavings: string
  /** ☆☆☆ ✔ "Cancel selected" */
  DefaultEraseOption: string
  /** ☆☆☆ ✔ 19 */
  DeletedImageCount: number
  /** ☆☆☆   "Berlin" */
  DestinationCity: string
  /** ☆☆☆   "No" */
  DestinationDST: string
  /** ☆☆☆ ✔ 100 */
  DevelopmentDynamicRange: number
  /** ☆☆☆   "Compact Digital Camera" */
  DeviceType: string
  /** ☆☆☆ ✔ "Normal" */
  DialDirectionTvAv: string
  /** ☆☆☆ ✔ undefined */
  DigitalGain: number
  /** ☆☆☆ ✔ 1 */
  DigitalZoom: number
  /** ☆☆☆   "Off" */
  DigitalZoomOn: string
  /** ☆☆☆ ✔ 100 */
  DirectoryIndex: number
  /** ☆☆☆ ✔ 103 */
  DirectoryIndex2: number
  /** ☆☆☆ ✔ 806 */
  DirectoryNumber: number
  /** ☆☆☆ ✔ "Enable" */
  DisplayAllAFPoints: string
  /** ☆☆☆ ✔ 3.9 */
  DisplayAperture: number
  /** ☆☆☆ ✔ "None" */
  DistortionCorrection: string
  /** ☆☆☆ ✔ "Off" */
  DistortionCorrection2: string
  /** ☆☆☆ ✔ "Off" */
  DistortionCorrectionSetting: string
  /** ☆☆☆   "Single-frame" */
  DriveMode2: string
  /** ☆☆☆ ✔ "(Binary data 1024 bytes, use -b option to extract)" */
  DustRemovalData: string
  /** ☆☆☆ ✔ "9 Points" */
  DynamicAFArea: string
  /** ☆☆☆ ✔ "On" */
  DynamicAreaAFDisplay: string
  /** ☆☆☆ ✔ "Standard" */
  DynamicRange: string
  /** ☆☆☆   "Off; 0; 0; 0" */
  DynamicRangeExpansion: string
  /** ☆☆☆ ✔ "Auto" */
  DynamicRangeOptimizer: string
  /** ☆☆☆ ✔ "Manual" */
  DynamicRangeSetting: string
  /** ☆☆☆ ✔ "Evaluative" */
  ETTLII: string
  /** ☆☆☆ ✔ "Off" */
  EasyExposureCompensation: string
  /** ☆☆☆ ✔ "Manual" */
  EasyMode: string
  /** ☆☆☆   3.8 */
  EffectiveLV: number
  /** ☆☆☆ ✔ 2 */
  EffectiveMaxAperture: number
  /** ☆☆☆   0.39 */
  Emissivity: number
  /** ☆☆☆ ✔ "0100" */
  EquipmentVersion: string
  /** ☆☆☆ ✔ "93.1 mm" */
  ExitPupilPosition: string
  /** ☆☆☆ ✔ "+162113114" */
  ExposureBracketValue: number
  /** ☆☆☆ ✔ "1/3 EV" */
  ExposureCompStepSize: string
  /** ☆☆☆ ✔ "1/3 EV" */
  ExposureControlStepSize: string
  /** ☆☆☆ ✔ 1 */
  ExposureCount: number
  /** ☆☆☆ ✔ "Off" */
  ExposureDelayMode: string
  /** ☆☆☆ ✔ -2.7 */
  ExposureDifference: number
  /** ☆☆☆ ✔ "1/3 Stop" */
  ExposureLevelIncrements: string
  /** ☆☆☆ ✔ "Spot metering" */
  ExposureModeInManual: string
  /** ☆☆☆ ✔ "undef" */
  ExposureShift: number
  /** ☆☆☆ ✔ "-1/2" */
  ExposureTuning: number
  /** ☆☆☆ ✔ "Good" */
  ExposureWarning: string
  /** ☆☆☆ ✔ "Off" */
  ExtendedWBDetect: string
  /** ☆☆☆ ✔ "None" */
  Extender: string
  /** ☆☆☆ ✔ undefined */
  ExtenderFirmwareVersion: number
  /** ☆☆☆ ✔ undefined */
  ExtenderModel: string
  /** ☆☆☆ ✔ undefined */
  ExtenderSerialNumber: string
  /** ☆☆☆ ✔ "Off" */
  ExternalFlash: string
  /** ☆☆☆ ✔ "Bounce or Off" */
  ExternalFlashBounce: string
  /** ☆☆☆ ✔ "-2/3" */
  ExternalFlashExposureComp: number
  /** ☆☆☆ ✔ "n/a" */
  ExternalFlashFirmware: string
  /** ☆☆☆ ✔ "(none)" */
  ExternalFlashFlags: string
  /** ☆☆☆ ✔ "n/a" */
  ExternalFlashReadyState: string
  /** ☆☆☆ ✔ "Flash Not Attached" */
  ExternalFlashStatus: string
  /** ☆☆☆ ✔ 54 */
  ExternalFlashZoom: number
  /** ☆☆☆ ✔ "No" */
  ExternalFlashZoomOverride: string
  /** ☆☆☆ ✔ "Enable; 0; 8; 0" */
  FEMicroadjustment: string
  /** ☆☆☆   "12 -54" */
  Face1Position: string
  /** ☆☆☆   "On (5 faces max); 0 faces detected; 0" */
  FaceDetect: string
  /** ☆☆☆ ✔ "(Binary data 383 bytes, use -b option to extract)" */
  FaceDetectArea: string
  /** ☆☆☆ ✔ "0 0 640 480 0 0 640 480 0 0 0 0" */
  FaceDetectFrameCrop: string
  /** ☆☆☆ ✔ "320 240" */
  FaceDetectFrameSize: string
  /** ☆☆☆ ✔ 37 */
  FaceInfoLength: number
  /** ☆☆☆ ✔ 94 */
  FaceInfoOffset: number
  /** ☆☆☆   "0 0" */
  FacePosition: string
  /** ☆☆☆   "Off" */
  FaceRecognition: string
  /** ☆☆☆   35 */
  FaceWidth: number
  /** ☆☆☆ ✔ 1 */
  FacesDetected: number
  /** ☆☆☆ ✔ 12336 */
  FacesRecognized: number
  /** ☆☆☆ ✔ "JPEG (lossy/non-quantization toggled)" */
  FileFormat: string
  /** ☆☆☆ ✔ 285 */
  FileIndex: number
  /** ☆☆☆ ✔ 1 */
  FileIndex2: number
  /** ☆☆☆ ✔ "0100" */
  FileInfoVersion: string
  /** ☆☆☆ ✔ "On" */
  FileNumberSequence: string
  /** ☆☆☆ ✔ "Enable" */
  FillFlashAutoReduction: string
  /** ☆☆☆ ✔ "F0/Standard (Provia)" */
  FilmMode: string
  /** ☆☆☆ ✔ "None" */
  FilterEffect: string
  /** ☆☆☆ ✔ "n/a" */
  FilterEffectAuto: string
  /** ☆☆☆ ✔ "None" */
  FilterEffectMonochrome: string
  /** ☆☆☆ ✔ "None" */
  FilterEffectUserDef1: string
  /** ☆☆☆ ✔ "None" */
  FilterEffectUserDef2: string
  /** ☆☆☆ ✔ "None" */
  FilterEffectUserDef3: string
  /** ☆☆☆ ✔ "Off" */
  FinderDisplayDuringExposure: string
  /** ☆☆☆   "73" */
  Firmware: string
  /** ☆☆☆ ✔ "1.00 rev 3.00" */
  FirmwareRevision: string
  /** ☆☆☆ ✔ "1.0.3" */
  FirmwareVersion: string
  /** ☆☆☆ ✔ "Off" */
  FisheyeFilter: string
  /** ☆☆☆ ✔ "Did not fire" */
  FlashAction: string
  /** ☆☆☆ ✔ 1 */
  FlashActivity: number
  /** ☆☆☆ ✔ "n/a" */
  FlashBatteryLevel: string
  /** ☆☆☆ ✔ "+2" */
  FlashBias: number
  /** ☆☆☆ ✔ "(none)" */
  FlashBits: string
  /** ☆☆☆ ✔ "Raise built-in flash" */
  FlashButtonFunction: string
  /** ☆☆☆ ✔ "Off" */
  FlashCommanderMode: string
  /** ☆☆☆ ✔ "-2/3" */
  FlashCompensation: number
  /** ☆☆☆ ✔ "Off" */
  FlashControlMode: string
  /** ☆☆☆ ✔ "n/a" */
  FlashCurtain: string
  /** ☆☆☆ ✔ 0.3 */
  FlashExposureBracketValue: number
  /** ☆☆☆ ✔ "+2" */
  FlashExposureComp: number
  /** ☆☆☆ ✔ "Entire frame" */
  FlashExposureCompArea: string
  /** ☆☆☆   -2 */
  FlashExposureCompSet: number
  /** ☆☆☆ ✔ "Off" */
  FlashExposureLock: string
  /** ☆☆☆ ✔ false */
  FlashFired: boolean
  /** ☆☆☆ ✔ "Fires" */
  FlashFiring: string
  /** ☆☆☆ ✔ 1 */
  FlashFirmwareVersion: number
  /** ☆☆☆ ✔ "12 mm" */
  FlashFocalLength: string
  /** ☆☆☆ ✔ "n/a" */
  FlashGNDistance: number
  /** ☆☆☆ ✔ undefined */
  FlashGroupACompensation: number
  /** ☆☆☆ ✔ "Off" */
  FlashGroupAControlMode: string
  /** ☆☆☆ ✔ undefined */
  FlashGroupBCompensation: number
  /** ☆☆☆ ✔ "Off" */
  FlashGroupBControlMode: string
  /** ☆☆☆ ✔ undefined */
  FlashGroupCCompensation: number
  /** ☆☆☆ ✔ "Off" */
  FlashGroupCControlMode: string
  /** ☆☆☆ ✔ 8.46875 */
  FlashGuideNumber: number
  /** ☆☆☆ ✔ "0100" */
  FlashInfoVersion: string
  /** ☆☆☆ ✔ "n/a (x4)" */
  FlashIntensity: string
  /** ☆☆☆ ✔ "Normal" */
  FlashLevel: string
  /** ☆☆☆ ✔ "Off" */
  FlashMeteringMode: string
  /** ☆☆☆   "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" */
  FlashMeteringSegments: string
  /** ☆☆☆ ✔ "Auto, Fired" */
  FlashMode: string
  /** ☆☆☆ ✔ "None" */
  FlashModel: string
  /** ☆☆☆ ✔ 175 */
  FlashOutput: number
  /** ☆☆☆ ✔ "Off" */
  FlashRemoteControl: string
  /** ☆☆☆ ✔ "01114671" */
  FlashSerialNumber: string
  /** ☆☆☆ ✔ "Normal" */
  FlashSetting: string
  /** ☆☆☆ ✔ "1/60 s" */
  FlashShutterSpeed: string
  /** ☆☆☆ ✔ "None" */
  FlashSource: string
  /** ☆☆☆ ✔ "Built-in Flash present" */
  FlashStatus: string
  /** ☆☆☆ ✔ "1/250 s" */
  FlashSyncSpeed: string
  /** ☆☆☆ ✔ "Auto" */
  FlashSyncSpeedAv: string
  /** ☆☆☆   "Yes (flash required but disabled)" */
  FlashWarning: string
  /** ☆☆☆ ✔ "0 0" */
  FlexibleSpotPosition: string
  /** ☆☆☆   "Off" */
  FlickerReduce: string
  /** ☆☆☆ ✔ "6.59 mm" */
  FocalPlaneDiagonal: string
  /** ☆☆☆ ✔ "5.41 mm" */
  FocalPlaneXSize: string
  /** ☆☆☆ ✔ "4.06 mm" */
  FocalPlaneYSize: string
  /** ☆☆☆ ✔ "Zoom" */
  FocalType: string
  /** ☆☆☆ ✔ "100/mm" */
  FocalUnits: string
  /** ☆☆☆ ✔ "Continuous" */
  FocusContinuous: string
  /** ☆☆☆ ✔ "Enable" */
  FocusDisplayAIServoAndMF: string
  /** ☆☆☆ ✔ "2.11 m" */
  FocusDistance: string
  /** ☆☆☆ ✔ "0 m" */
  FocusDistanceLower: string
  /** ☆☆☆ ✔ "65.53 m" */
  FocusDistanceUpper: string
  /** ☆☆☆ ✔ "0100" */
  FocusInfoVersion: string
  /** ★☆☆ ✔ "Single-Area Auto Focus" */
  FocusMode: string
  /** ☆☆☆   "AF-S" */
  FocusMode2: string
  /** ☆☆☆ ✔ "1832 1374" */
  FocusPixel: string
  /** ☆☆☆ ✔ "No Wrap" */
  FocusPointWrap: string
  /** ☆☆☆ ✔ "0x11" */
  FocusPosition: number
  /** ☆☆☆ ✔ 205 */
  FocusPosition2: number
  /** ☆☆☆ ✔ "AF Not Used; 0" */
  FocusProcess: string
  /** ☆☆☆ ✔ "Auto" */
  FocusRange: string
  /** ☆☆☆   "7 (very far)" */
  FocusRangeIndex: number
  /** ☆☆☆ ✔ 286 */
  FocusStepCount: number
  /** ☆☆☆ ✔ 9626 */
  FocusStepInfinity: number
  /** ☆☆☆ ✔ 9718 */
  FocusStepNear: number
  /** ☆☆☆ ✔ "3 (Normal)" */
  FocusTrackingLockOn: string
  /** ☆☆☆ ✔ "Good" */
  FocusWarning: string
  /** ☆☆☆ ✔ "Ec-CIV" */
  FocusingScreen: string
  /** ☆☆☆   1 */
  FrameNumber: number
  /** ☆☆☆ ✔ "Off" */
  FujiFlashMode: string
  /** ☆☆☆ ✔ "6000x4000" */
  FullImageSize: string
  /** ☆☆☆ ✔ "Virtual Horizon" */
  FuncButton: string
  /** ☆☆☆ ✔ "None" */
  FuncButtonPlusDials: string
  /** ☆☆☆ ✔ 256 */
  GainBase: number
  /** ☆☆☆ ✔ "Normal; User-Selected" */
  Gradation: string
  /** ☆☆☆ ✔ "Off" */
  GrainyBWFilter: string
  /** ☆☆☆ ✔ "On" */
  GridDisplay: string
  /** ☆☆☆ ✔ "Squares" */
  GroupAreaAFIllumination: string
  /** ☆☆☆ ✔ "Off" */
  HDR: string
  /** ☆☆☆ ✔ "Natural" */
  HDREffect: string
  /** ☆☆☆ ✔ "Unknown (2)" */
  HDRImageType: string
  /** ☆☆☆ ✔ "0200" */
  HDRInfoVersion: string
  /** ☆☆☆ ✔ "Auto" */
  HDRLevel: string
  /** ☆☆☆   "Auto" */
  HDRLevel2: string
  /** ☆☆☆ ✔ "Off" */
  HDRSetting: string
  /** ☆☆☆   "Off" */
  HDRSmoothing: string
  /** ☆☆☆ ✔ "Off" */
  HighISONoiseReduction: string
  /** ☆☆☆   "Normal" */
  HighISONoiseReduction2: string
  /** ☆☆☆ ✔ "0 (normal)" */
  HighlightTone: string
  /** ☆☆☆ ✔ "Disable" */
  HighlightTonePriority: string
  /** ☆☆☆   "ndon" */
  HometownCity: string
  /** ☆☆☆   "No" */
  HometownDST: string
  /** ☆☆☆ ✔ "None" */
  Hue: string
  /** ☆☆☆ ✔ 3 */
  HueAdjustment: string
  /** ☆☆☆ ✔ 100 */
  ISO2: number
  /** ☆☆☆ ✔ "ISO 1600" */
  ISOAutoHiLimit: string
  /** ☆☆☆ ✔ "Auto" */
  ISOAutoShutterTime: string
  /** ☆☆☆ ✔ "Show Frame Count" */
  ISODisplay: string
  /** ☆☆☆ ✔ "On" */
  ISOExpansion: string
  /** ☆☆☆ ✔ "Off" */
  ISOExpansion2: string
  /** ☆☆☆   "Auto" */
  ISOSelection: string
  /** ☆☆☆ ✔ 250 */
  ISOSetting: number
  /** ☆☆☆ ✔ "Yes" */
  ISOSpeedExpansion: string
  /** ☆☆☆ ✔ "1/3 Stop" */
  ISOSpeedIncrements: string
  /** ☆☆☆ ✔ "Disable; Max 3200; Min 100" */
  ISOSpeedRange: string
  /** ☆☆☆ ✔ "1/3 EV" */
  ISOStepSize: string
  /** ☆☆☆   "Auto" */
  ImageAdjustment: string
  /** ☆☆☆ ✔ "Off" */
  ImageAuthentication: string
  /** ☆☆☆ ✔ "0 0 4288 2848" */
  ImageBoundary: string
  /** ☆☆☆ ✔ 1 */
  ImageCount: number
  /** ☆☆☆ ✔ 130 */
  ImageCount3: number
  /** ☆☆☆ ✔ 4996902 */
  ImageDataSize: number
  /** ☆☆☆   1 */
  ImageEditCount: number
  /** ☆☆☆   "None" */
  ImageEditing: string
  /** ☆☆☆ ✔ "Original Image" */
  ImageGeneration: string
  /** ☆☆☆ ✔ "Normal" */
  ImageOptimization: string
  /** ☆☆☆   "                   \u0000                   \u0000" */
  ImageProcessing: string
  /** ☆☆☆ ✔ "0112" */
  ImageProcessingVersion: string
  /** ☆☆☆ ✔ "NEF (RAW) + JPEG Fine" */
  ImageQuality: string
  /** ☆☆☆ ✔ "4 s" */
  ImageReviewMonitorOffTime: string
  /** ☆☆☆ ✔ "Off" */
  ImageStabilization: string
  /** ☆☆☆   0.9238126655 */
  ImageTemperatureMax: number
  /** ☆☆☆   0.9914525824 */
  ImageTemperatureMin: number
  /** ☆☆☆   "Bright" */
  ImageTone: string
  /** ☆☆☆ ✔ "Displays camera settings" */
  InfoButtonWhenShooting: string
  /** ☆☆☆ ✔ "Medium Magnification" */
  InitialZoomSetting: string
  /** ☆☆☆ ✔ "Off" */
  IntelligentAuto: string
  /** ☆☆☆ ✔ "Off" */
  IntelligentContrast: string
  /** ☆☆☆   "Off" */
  IntelligentExposure: string
  /** ☆☆☆ ✔ "Extended" */
  IntelligentResolution: string
  /** ☆☆☆ ✔ "Off" */
  InternalFlash: string
  /** ☆☆☆ ✔ "undef" */
  InternalNDFilter: number
  /** ☆☆☆ ✔ 509143782 */
  InternalSerialNumber: string
  /** ☆☆☆ ✔ 8 */
  JPEGQuality: string
  /** ☆☆☆ ✔ "Off" */
  KeystoneCompensation: string
  /** ☆☆☆ ✔ "Vertical" */
  KeystoneDirection: string
  /** ☆☆☆ ✔ "0 -20 20" */
  KeystoneValue: string
  /** ☆☆☆   600 */
  KodakImageHeight: number
  /** ☆☆☆   800 */
  KodakImageWidth: number
  /** ☆☆☆   "HP PhotoSmart 618" */
  KodakModel: string
  /** ☆☆☆ ✔ "Display" */
  LCDDisplayAtPowerOn: string
  /** ☆☆☆ ✔ "Off" */
  LCDIllumination: string
  /** ☆☆☆ ✔ "Off" */
  LCDIlluminationDuringBulb: string
  /** ☆☆☆ ✔ "Remain. shots/File no." */
  LCDPanels: string
  /** ☆☆☆ ✔ "Masked" */
  LVShootingAreaDisplay: string
  /** ☆☆☆ ✔ "---" */
  Landmark: string
  /** ☆☆☆ ✔ "Auto" */
  LateralChromaticAberration: string
  /** ☆☆☆ ✔ "AF Stop" */
  LensAFStopButton: string
  /** ☆☆☆ ✔ "0201" */
  LensDataVersion: string
  /** ☆☆☆   "-176 -386 -470 -186 -412 -504" */
  LensDistortionParams: string
  /** ☆☆☆ ✔ "Focus search on" */
  LensDriveNoAF: string
  /** ☆☆☆ ✔ "Continue Focus Search" */
  LensDriveWhenAFImpossible: string
  /** ☆☆☆ ✔ 7 */
  LensFStops: number
  /** ☆☆☆ ✔ "Ver.02" */
  LensFirmwareVersion: string
  /** ☆☆☆   "55.0 mm" */
  LensFocalLength: string
  /** ☆☆☆ ✔ "AF Lock Only" */
  LensFocusFunctionButtons: string
  /** ☆☆☆ ✔ "APS-C" */
  LensFormat: string
  /** ☆☆☆ ✔ 129 */
  LensIDNumber: number
  /** ☆☆☆ ✔ "E-mount" */
  LensMount: string
  /** ☆☆☆ ✔ "E-mount" */
  LensMount2: string
  /** ☆☆☆ ✔ "0xc140" */
  LensProperties: string
  /** ☆☆☆ ✔ "E OSS" */
  LensSpecFeatures: string
  /** ☆☆☆ ✔ "n/a" */
  LensType: string
  /** ☆☆☆ ✔ "Sony E 18-55mm F3.5-5.6 OSS" */
  LensType2: string
  /** ☆☆☆ ✔ "Sony E 18-55mm F3.5-5.6 OSS" */
  LensType3: string
  /** ☆☆☆ ✔ "2%" */
  LensZoomPosition: string
  /** ☆☆☆   15 */
  LightReading: number
  /** ☆☆☆   "Off" */
  LightSourceSpecial: string
  /** ☆☆☆ ✔ "LCD Backlight" */
  LightSwitch: string
  /** ☆☆☆ ✔ "No Restrictions" */
  LimitAFAreaModeSelection: string
  /** ☆☆☆ ✔ 10000 */
  LinearityUpperMargin: number
  /** ☆☆☆ ✔ "Enable" */
  LiveViewButtonOptions: string
  /** ☆☆☆ ✔ "Enable (simulates exposure)" */
  LiveViewExposureSimulation: string
  /** ☆☆☆ ✔ "10 min" */
  LiveViewMonitorOffTime: string
  /** ☆☆☆ ✔ "Off" */
  LiveViewShooting: string
  /** ☆☆☆ ✔ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000… */
  Location: string
  /** ☆☆☆ ✔ "Protect (hold:record memo)" */
  LockMicrophoneButton: string
  /** ☆☆☆ ✔ "Off" */
  LongExposureNoiseReduction: string
  /** ☆☆☆ ✔ "Off" */
  LongExposureNoiseReduction2: string
  /** ☆☆☆ ✔ 134 */
  MCUVersion: number
  /** ☆☆☆ ✔ "Off" */
  Macro: string
  /** ☆☆☆ ✔ "Off" */
  MacroLED: string
  /** ☆☆☆ ✔ "Unknown (0)" */
  MacroMode: string
  /** ☆☆☆ ✔ "Off; 0; 0; 0" */
  MagicFilter: string
  /** ☆☆☆ ✔ "Image playback only" */
  MagnifiedView: string
  /** ☆☆☆   "MKED" */
  MakerNoteType: string
  /** ☆☆☆ ✔ 2.1 */
  MakerNoteVersion: string
  /** ☆☆☆ ✔ "0 kPa" */
  ManometerPressure: string
  /** ☆☆☆ ✔ "0 m, 0 ft" */
  ManometerReading: string
  /** ☆☆☆ ✔ "Stops at AF Area Edges" */
  ManualAFPointSelPattern: string
  /** ☆☆☆ ✔ "Stops at AF area edges" */
  ManualAFPointSelectPattern: string
  /** ☆☆☆ ✔ "Off" */
  ManualFlash: string
  /** ☆☆☆ ✔ "n/a" */
  ManualFlashOutput: string
  /** ☆☆☆ ✔ "n/a (x4)" */
  ManualFlashStrength: string
  /** ☆☆☆   "undef" */
  ManualFocusDistance: string
  /** ☆☆☆ ✔ "Tv=Main/Av=Control" */
  ManualTv: string
  /** ☆☆☆   "Unknown (0)" */
  ManufactureDate: ExifDate
  /** ☆☆☆   "2004:04:14          " */
  ManufactureDate1: ExifDateTime
  /** ☆☆☆   "2004:02:17          " */
  ManufactureDate2: string
  /** ☆☆☆ ✔ "Face Detection On" */
  MatrixMetering: string
  /** ☆☆☆ ✔ 32 */
  MaxAperture: number
  /** ☆☆☆ ✔ 4.5 */
  MaxApertureAtMaxFocal: number
  /** ☆☆☆ ✔ 3.5 */
  MaxApertureAtMinFocal: number
  /** ☆☆☆ ✔ 100 */
  MaxContinuousRelease: number
  /** ☆☆☆ ✔ "8 8 0" */
  MaxFaces: string
  /** ☆☆☆ ✔ "57.6 mm" */
  MaxFocalLength: string
  /** ☆☆☆ ✔ 5 */
  MeasuredEV: number
  /** ☆☆☆ ✔ 12.625 */
  MeasuredEV2: number
  /** ☆☆☆ ✔ 11.25 */
  MeasuredEV3: number
  /** ☆☆☆ ✔ "471 1024 1024 581" */
  MeasuredRGGB: string
  /** ☆☆☆ ✔ "28263 52181 52475 22264" */
  MeasuredRGGBData: string
  /** ☆☆☆ ✔ 1 */
  MemoryCardNumber: number
  /** ☆☆☆ ✔ "1 min" */
  MenuMonitorOffTime: string
  /** ☆☆☆ ✔ "DC7303320222000" */
  MetaVersion: string
  /** ☆☆☆ ✔ "30 s" */
  MeteringTime: string
  /** ☆☆☆ ✔ 6.9 */
  MinAperture: number
  /** ☆☆☆ ✔ "4.8 mm" */
  MinFocalLength: string
  /** ☆☆☆   "0.25-0.28 m" */
  MinFocusDistance: string
  /** ☆☆☆ ✔ "Off" */
  MiniatureFilter: string
  /** ☆☆☆ ✔ "Horizontal" */
  MiniatureFilterOrientation: string
  /** ☆☆☆ ✔ -1 */
  MiniatureFilterParameter: number
  /** ☆☆☆ ✔ -1 */
  MiniatureFilterPosition: number
  /** ☆☆☆   "Extra fine" */
  MinoltaQuality: string
  /** ☆☆☆ ✔ "Disable" */
  MirrorLockup: string
  /** ☆☆☆ ✔ 2011 */
  ModelReleaseYear: number
  /** ☆☆☆ ✔ "On" */
  ModelingFlash: string
  /** ☆☆☆ ✔ "Off" */
  ModifiedSaturation: string
  /** ☆☆☆ ✔ "1 min" */
  MonitorOffTime: string
  /** ☆☆☆   "None" */
  MonochromeToning: string
  /** ☆☆☆   "11:19" */
  MonthDayCreated: string
  /** ☆☆☆ ✔ "AE/AF Lock" */
  MovieAELockButtonAssignment: string
  /** ☆☆☆ ✔ "None" */
  MovieFunctionButton: string
  /** ☆☆☆ ✔ "Index Marking" */
  MoviePreviewButton: string
  /** ☆☆☆ ✔ "Take Photo" */
  MovieShutterButton: string
  /** ☆☆☆ ✔ "Off" */
  MultiControllerWhileMetering: string
  /** ☆☆☆ ✔ "Off" */
  MultiExposure: string
  /** ☆☆☆ ✔ "Off" */
  MultiExposureAutoGain: string
  /** ☆☆☆ ✔ "Additive" */
  MultiExposureControl: string
  /** ☆☆☆ ✔ "Off" */
  MultiExposureMode: string
  /** ☆☆☆ ✔ 1 */
  MultiExposureShots: number
  /** ☆☆☆ ✔ "0100" */
  MultiExposureVersion: string
  /** ☆☆☆ ✔ "Off" */
  MultiFrameNoiseReduction: string
  /** ☆☆☆ ✔ "Off; Quick control dial" */
  MultiFunctionLock: string
  /** ☆☆☆ ✔ "Do Nothing" */
  MultiSelector: string
  /** ☆☆☆ ✔ "Reset" */
  MultiSelectorLiveView: string
  /** ☆☆☆ ✔ "Thumbnail On/Off" */
  MultiSelectorPlaybackMode: string
  /** ☆☆☆ ✔ "Select Center Focus Point (Reset)" */
  MultiSelectorShootMode: string
  /** ☆☆☆ ✔ "Off; 1" */
  MultipleExposureMode: string
  /** ☆☆☆ ✔ "Off" */
  MyColorMode: string
  /** ☆☆☆ ✔ "n/a" */
  NDFilter: string
  /** ☆☆☆   "n/a (JPEG)" */
  NEFBitDepth: string
  /** ☆☆☆ ✔ "Lossy (type 2)" */
  NEFCompression: string
  /** ☆☆☆ ✔ "(Binary data 624 bytes, use -b option to extract)" */
  NEFLinearizationTable: string
  /** ☆☆☆   "OTHER" */
  NikonCaptureVersion: string
  /** ☆☆☆ ✔ "Large" */
  NikonImageSize: string
  /** ☆☆☆ ✔ "Enable Release" */
  NoMemoryCard: string
  /** ☆☆☆ ✔ "Standard" */
  NoiseFilter: string
  /** ☆☆☆ ✔ "Off" */
  NoiseReduction: string
  /** ☆☆☆ ✔ "(none)" */
  NoiseReduction2: string
  /** ☆☆☆   5.7 */
  NominalMaxAperture: number
  /** ☆☆☆   38 */
  NominalMinAperture: number
  /** ☆☆☆ ✔ 14582 */
  NormalWhiteLevel: number
  /** ☆☆☆ ✔ 9 */
  NumAFPoints: number
  /** ☆☆☆ ✔ 1 */
  NumFacePositions: number
  /** ☆☆☆ ✔ "Focus Priority" */
  OneShotAFRelease: string
  /** ☆☆☆   "Unknown ()" */
  OneTouchWB: string
  /** ☆☆☆   1 */
  OpticalZoom: number
  /** ☆☆☆ ✔ "n/a" */
  OpticalZoomCode: number
  /** ☆☆☆ ✔ "Standard" */
  OpticalZoomMode: string
  /** ☆☆☆   "Off" */
  OpticalZoomOn: string
  /** ☆☆☆ ✔ "Same for Vert/Horiz Points" */
  OrientationLinkedAF: string
  /** ☆☆☆ ✔ "Same for vertical and horizontal" */
  OrientationLinkedAFPoint: string
  /** ☆☆☆ ✔ 3318 */
  OriginalDecisionDataOffset: number
  /** ☆☆☆ ✔ 3456 */
  OriginalImageHeight: number
  /** ☆☆☆ ✔ 5184 */
  OriginalImageWidth: number
  /** ☆☆☆ ✔ "Off" */
  PF0CustomFuncRegistration: string
  /** ☆☆☆ ✔ "Off" */
  PF10RetainProgramShift: string
  /** ☆☆☆ ✔ "Off" */
  PF13DrivePriority: string
  /** ☆☆☆ ✔ "Off" */
  PF14DisableFocusSearch: string
  /** ☆☆☆ ✔ "Off" */
  PF15DisableAFAssistBeam: string
  /** ☆☆☆ ✔ "Off" */
  PF16AutoFocusPointShoot: string
  /** ☆☆☆ ✔ "Off" */
  PF17DisableAFPointSel: string
  /** ☆☆☆ ✔ "Off" */
  PF18EnableAutoAFPointSel: string
  /** ☆☆☆ ✔ "Off" */
  PF19ContinuousShootSpeed: string
  /** ☆☆☆ ✔ 14 */
  PF19ShootingSpeedHigh: number
  /** ☆☆☆ ✔ 4 */
  PF19ShootingSpeedLow: number
  /** ☆☆☆ ✔ "Off" */
  PF1DisableShootingModes: string
  /** ☆☆☆ ✔ 63 */
  PF1Value: number
  /** ☆☆☆ ✔ "Off" */
  PF20LimitContinousShots: string
  /** ☆☆☆ ✔ 21 */
  PF20MaxContinousShots: number
  /** ☆☆☆ ✔ "Off" */
  PF21EnableQuietOperation: string
  /** ☆☆☆ ✔ 256 */
  PF23FELockTime: number
  /** ☆☆☆ ✔ 32 */
  PF23PostReleaseTime: number
  /** ☆☆☆ ✔ "Off" */
  PF23SetTimerLengths: string
  /** ☆☆☆ ✔ 96 */
  PF23ShutterButtonTime: number
  /** ☆☆☆ ✔ "Off" */
  PF24LightLCDDuringBulb: string
  /** ☆☆☆ ✔ 16 */
  PF25AEMode: number
  /** ☆☆☆ ✔ 130 */
  PF25AFMode: number
  /** ☆☆☆ ✔ 255 */
  PF25AFPointSel: number
  /** ☆☆☆ ✔ 1 */
  PF25ColorMatrix: number
  /** ☆☆☆ ✔ "Off" */
  PF25DefaultClearSettings: string
  /** ☆☆☆ ✔ 4 */
  PF25DriveMode: number
  /** ☆☆☆ ✔ 2 */
  PF25ImageSize: number
  /** ☆☆☆ ✔ 32 */
  PF25MeteringMode: number
  /** ☆☆☆ ✔ 1 */
  PF25Parameters: number
  /** ☆☆☆ ✔ 1 */
  PF25WBMode: number
  /** ☆☆☆ ✔ "Off" */
  PF26ShortenReleaseLag: string
  /** ☆☆☆ ✔ "Off" */
  PF27ReverseDialRotation: string
  /** ☆☆☆ ✔ 2 */
  PF27Value: number
  /** ☆☆☆ ✔ "Off" */
  PF28NoQuickDialExpComp: string
  /** ☆☆☆ ✔ "Off" */
  PF29QuickDialSwitchOff: string
  /** ☆☆☆ ✔ "Off" */
  PF2DisableMeteringModes: string
  /** ☆☆☆ ✔ 240 */
  PF2Value: number
  /** ☆☆☆ ✔ "Off" */
  PF30EnlargementMode: string
  /** ☆☆☆ ✔ "Off" */
  PF31OriginalDecisionData: string
  /** ☆☆☆ ✔ "Off" */
  PF3ManualExposureMetering: string
  /** ☆☆☆ ✔ 16 */
  PF3Value: number
  /** ☆☆☆ ✔ "Off" */
  PF4ExposureTimeLimits: string
  /** ☆☆☆ ✔ 31.2 */
  PF4ExposureTimeMax: number
  /** ☆☆☆ ✔ "1/16777" */
  PF4ExposureTimeMin: string
  /** ☆☆☆ ✔ "Off" */
  PF5ApertureLimits: string
  /** ☆☆☆ ✔ 1 */
  PF5ApertureMax: number
  /** ☆☆☆ ✔ 91 */
  PF5ApertureMin: number
  /** ☆☆☆ ✔ "Off" */
  PF6PresetShootingModes: string
  /** ☆☆☆ ✔ "Off" */
  PF7BracketContinuousShoot: string
  /** ☆☆☆ ✔ 3 */
  PF8BracketShots: number
  /** ☆☆☆ ✔ "Off" */
  PF8SetBracketShots: string
  /** ☆☆☆ ✔ "Off" */
  PF9ChangeBracketSequence: string
  /** ☆☆☆ ✔ "Off" */
  PaintingFilter: string
  /** ☆☆☆ ✔ "0405" */
  PanasonicExifVersion: string
  /** ☆☆☆ ✔ 3424 */
  PanasonicImageHeight: number
  /** ☆☆☆ ✔ 3424 */
  PanasonicImageWidth: number
  /** ☆☆☆ ✔ "Off" */
  PanoramaMode: string
  /** ☆☆☆   "640x480" */
  PentaxImageSize: string
  /** ☆☆☆   "Optio T10/T20" */
  PentaxModelID: string
  /** ☆☆☆   4 */
  PentaxModelType: number
  /** ☆☆☆   "6.0.0.0" */
  PentaxVersion: string
  /** ☆☆☆ ✔ "1023 1024 1023 1024" */
  PerChannelBlackLevel: string
  /** ☆☆☆ ✔ "On" */
  PeripheralIlluminationCorr: string
  /** ☆☆☆ ✔ "Off" */
  PeripheralLighting: string
  /** ☆☆☆ ✔ "Off" */
  PeripheralLightingSetting: string
  /** ☆☆☆ ✔ 70 */
  PeripheralLightingValue: number
  /** ☆☆☆ ✔ "Off" */
  PhaseDetectAF: string
  /** ☆☆☆ ✔ "Off" */
  PhotoEffect: string
  /** ☆☆☆ ✔ "Info Up-down, Playback Left-right" */
  PhotoInfoPlayback: string
  /** ☆☆☆ ✔ "Standard or Custom" */
  PhotoStyle: string
  /** ☆☆☆ ✔ "Full Control" */
  PictureControlAdjust: string
  /** ☆☆☆ ✔ "Landscape" */
  PictureControlBase: string
  /** ☆☆☆ ✔ "Landscape" */
  PictureControlName: string
  /** ☆☆☆ ✔ "Normal" */
  PictureControlQuickAdjust: string
  /** ☆☆☆ ✔ "0200" */
  PictureControlVersion: string
  /** ☆☆☆ ✔ "Off" */
  PictureEffect: string
  /** ☆☆☆ ✔ "Off" */
  PictureEffect2: string
  /** ☆☆☆ ✔ "Program" */
  PictureMode: string
  /** ☆☆☆ ✔ "n/a" */
  PictureModeBWFilter: string
  /** ☆☆☆ ✔ "0 (min -2, max 2)" */
  PictureModeContrast: string
  /** ☆☆☆ ✔ "Standard" */
  PictureModeEffect: string
  /** ☆☆☆ ✔ "0 (min -2, max 2)" */
  PictureModeSaturation: string
  /** ☆☆☆ ✔ "0 (min -2, max 2)" */
  PictureModeSharpness: string
  /** ☆☆☆ ✔ "n/a" */
  PictureModeTone: string
  /** ☆☆☆ ✔ "Standard/Neutral - Gamma Still (PP2)" */
  PictureProfile: string
  /** ☆☆☆ ✔ "None" */
  PictureStyle: string
  /** ☆☆☆ ✔ "None; None; None" */
  PictureStylePC: string
  /** ☆☆☆ ✔ "Standard; Standard; Standard" */
  PictureStyleUserDef: string
  /** ☆☆☆ ✔ "+0.40" */
  Pitch: string
  /** ☆☆☆ ✔ 7303.4 */
  PitchAngle: number
  /** ☆☆☆ ✔ "10 s" */
  PlaybackMonitorOffTime: string
  /** ☆☆☆   "Body Battery" */
  PowerSource: string
  /** ☆☆☆ ✔ "0000:00:00 00:00:00" */
  PowerUpTime: ExifDateTime
  /** ☆☆☆   3.299610895 */
  PreCaptureFrames: number
  /** ☆☆☆ ✔ "Preview" */
  PreviewButton: string
  /** ☆☆☆ ✔ "None" */
  PreviewButtonPlusDials: string
  /** ☆☆☆   "26 26 0 0" */
  PreviewImageBorders: string
  /** ☆☆☆ ✔ "Yes" */
  PreviewImageValid: string
  /** ☆☆☆ ✔ 4 */
  PrimaryAFPoint: number
  /** ☆☆☆   1.2 */
  ProductionCode: number
  /** ☆☆☆ ✔ 125 */
  ProgramISO: string
  /** ☆☆☆ ✔ undefined */
  ProgramShift: number
  /** ★☆☆ ✔ "Unknown (0)" */
  Quality: string
  /** ☆☆☆ ✔ "JPEG" */
  Quality2: string
  /** ☆☆☆ ✔ "Exposure comp/Aperture" */
  QuickControlDialInMeter: string
  /** ☆☆☆   "Off" */
  QuickShot: string
  /** ☆☆☆   "Little-endian (Intel, II)" */
  RawDataByteOrder: string
  /** ☆☆☆   "Swap" */
  RawDataCFAPattern: string
  /** ☆☆☆ ✔ "Off; 0; 0; 0" */
  RawDevArtFilter: string
  /** ☆☆☆ ✔ "Off" */
  RawDevAutoGradation: string
  /** ☆☆☆ ✔ "sRGB" */
  RawDevColorSpace: string
  /** ☆☆☆ ✔ "0 0 0" */
  RawDevContrastValue: string
  /** ☆☆☆ ✔ "Original" */
  RawDevEditStatus: string
  /** ☆☆☆ ✔ "High Speed" */
  RawDevEngine: string
  /** ☆☆☆ ✔ undefined */
  RawDevExposureBiasValue: number
  /** ☆☆☆ ✔ "0 0 0" */
  RawDevGrayPoint: string
  /** ☆☆☆ ✔ undefined */
  RawDevMemoryColorEmphasis: number
  /** ☆☆☆ ✔ "(none)" */
  RawDevNoiseReduction: string
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevPMContrast: string
  /** ☆☆☆ ✔ "1 -2 -2 1" */
  RawDevPMNoiseFilter: string
  /** ☆☆☆ ✔ "Unknown (0)" */
  RawDevPMPictureTone: string
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevPMSaturation: string
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevPMSharpness: string
  /** ☆☆☆ ✔ "Unknown (0)" */
  RawDevPM_BWFilter: string
  /** ☆☆☆ ✔ "Natural" */
  RawDevPictureMode: string
  /** ☆☆☆ ✔ "0 0 0" */
  RawDevSaturationEmphasis: string
  /** ☆☆☆ ✔ "(none)" */
  RawDevSettings: string
  /** ☆☆☆ ✔ "0 0 0" */
  RawDevSharpnessValue: string
  /** ☆☆☆ ✔ "0100" */
  RawDevVersion: string
  /** ☆☆☆ ✔ "0 0" */
  RawDevWBFineAdjustment: number
  /** ☆☆☆ ✔ "Unknown (3)" */
  RawDevWhiteBalance: string
  /** ☆☆☆ ✔ undefined */
  RawDevWhiteBalanceValue: number
  /** ☆☆☆ ✔ "3018 2010" */
  RawImageCenter: string
  /** ☆☆☆ ✔ 3288 */
  RawImageHeight: number
  /** ☆☆☆ ✔ 4952 */
  RawImageWidth: number
  /** ☆☆☆ ✔ "Fine" */
  RawJpgQuality: string
  /** ☆☆☆ ✔ "Large" */
  RawJpgSize: string
  /** ☆☆☆ ✔ "40661 82449 82146 41069" */
  RawMeasuredRGGB: string
  /** ☆☆☆ ✔ "ISO" */
  RearDisplay: string
  /** ☆☆☆ ✔ "Program AE" */
  RecordMode: string
  /** ☆☆☆   "Record while down" */
  RecordShutterRelease: string
  /** ☆☆☆ ✔ "No" */
  ReleaseButtonToUseDial: string
  /** ☆☆☆ ✔ "Unknown (7)" */
  ReleaseMode: string
  /** ☆☆☆ ✔ "Normal" */
  ReleaseMode2: string
  /** ☆☆☆ ✔ "Normal" */
  ReleaseMode3: string
  /** ☆☆☆   "No" */
  Resaved: string
  /** ☆☆☆   2 */
  Resolution: number
  /** ☆☆☆ ✔ "NEF Processing" */
  RetouchHistory: string
  /** ☆☆☆ ✔ "0200" */
  RetouchInfoVersion: string
  /** ☆☆☆ ✔ "On" */
  RetouchNEFProcessing: string
  /** ☆☆☆ ✔ "Disable" */
  RetractLensOnPowerOff: string
  /** ☆☆☆ ✔ "- 0 +" */
  ReverseIndicators: string
  /** ☆☆☆   {"year":2004,"month":6,"day":19,"hour":14,"minute":36,"second":43,"millis":0} */
  RicohDate: ExifDateTime
  /** ☆☆☆   1536 */
  RicohImageHeight: number
  /** ☆☆☆   2048 */
  RicohImageWidth: number
  /** ☆☆☆ ✔ 38279.7 */
  RollAngle: number
  /** ☆☆☆ ✔ 270 */
  Rotation: string
  /** ☆☆☆ ✔ "Valid" */
  RunTimeFlags: string
  /** ☆☆☆ ✔ 1000000000 */
  RunTimeScale: number
  /** ☆☆☆ ✔ 17795581340958 */
  RunTimeValue: number
  /** ☆☆☆ ✔ "0x44332211" */
  SR2SubIFDKey: string
  /** ☆☆☆ ✔ 29252 */
  SR2SubIFDLength: number
  /** ☆☆☆ ✔ 49086 */
  SR2SubIFDOffset: number
  /** ☆☆☆ ✔ "n/a" */
  SRAWQuality: string
  /** ☆☆☆ ✔ "Disable" */
  SafetyShift: string
  /** ☆☆☆ ✔ "Disable" */
  SafetyShiftInAvOrTv: string
  /** ☆☆☆   "Various Models (0x3000000)" */
  SamsungModelID: string
  /** ☆☆☆   "Unknown (0x11)" */
  SanyoQuality: string
  /** ☆☆☆ ✔ undefined */
  SaturationFaithful: number
  /** ☆☆☆ ✔ 4 */
  SaturationLandscape: number
  /** ☆☆☆ ✔ undefined */
  SaturationNeutral: number
  /** ☆☆☆ ✔ 2 */
  SaturationPortrait: number
  /** ☆☆☆ ✔ 3 */
  SaturationStandard: number
  /** ☆☆☆ ✔ 3 */
  SaturationUserDef1: number
  /** ☆☆☆ ✔ 4 */
  SaturationUserDef2: number
  /** ☆☆☆ ✔ 3 */
  SaturationUserDef3: number
  /** ☆☆☆   "Toy Camera Effect" */
  SceneAssist: string
  /** ☆☆☆ ✔ 2 */
  SceneDetect: number
  /** ☆☆☆ ✔ "Standard" */
  SceneMode: string
  /** ☆☆☆   "Off" */
  SceneSelect: string
  /** ☆☆☆ ✔ "On" */
  ScreenTips: string
  /** ☆☆☆ ✔ "Backup" */
  SecondarySlotFunction: string
  /** ☆☆☆ ✔ "Disable; Flags 0x7" */
  SelectAFAreaSelectMode: string
  /** ☆☆☆ ✔ "Single-point AF, Auto, Zone AF, AF Point Expansion (4 point), Spot AF, AF Poin… */
  SelectAFAreaSelectionMode: string
  /** ☆☆☆ ✔ "19 points" */
  SelectableAFPoint: string
  /** ☆☆☆ ✔ "Off" */
  SelfTimer: string
  /** ☆☆☆ ✔ 0.1 */
  SelfTimer2: number
  /** ☆☆☆ ✔ 2 */
  SelfTimerShotCount: number
  /** ☆☆☆ ✔ "1 s" */
  SelfTimerShotInterval: string
  /** ☆☆☆ ✔ "10 s" */
  SelfTimerTime: string
  /** ☆☆☆   undefined */
  SensitivityAdjust: number
  /** ☆☆☆ ✔ -1 */
  SensorBlueLevel: number
  /** ☆☆☆ ✔ "4094 256" */
  SensorCalibration: string
  /** ☆☆☆ ✔ "5.4 x 5.4 um" */
  SensorPixelSize: string
  /** ☆☆☆ ✔ -1 */
  SensorRedLevel: number
  /** ☆☆☆ ✔ "48 48 0 C" */
  SensorTemperature: string
  /** ☆☆☆ ✔ 1 */
  SequenceFileNumber: number
  /** ☆☆☆ ✔ 1 */
  SequenceImageNumber: number
  /** ☆☆☆ ✔ "1 shot" */
  SequenceLength: string
  /** ☆☆☆ ✔ 1 */
  SequenceNumber: number
  /** ☆☆☆   "5 frames/s" */
  SequenceShotInterval: string
  /** ☆☆☆   "Best" */
  SequentialShot: string
  /** ☆☆☆ ✔ "Format 2" */
  SerialNumberFormat: string
  /** ☆☆☆ ✔ "Normal" */
  SetButtonCrossKeysFunc: string
  /** ☆☆☆ ✔ "Default (no function)" */
  SetButtonWhenShooting: string
  /** ☆☆☆ ✔ "Off" */
  ShadingCompensation: string
  /** ☆☆☆ ✔ "Off" */
  ShadingCompensation2: string
  /** ☆☆☆   "Off" */
  ShadowCorrection: string
  /** ☆☆☆ ✔ "0 (normal)" */
  ShadowTone: string
  /** ☆☆☆   "Off (4)" */
  ShakeReduction: string
  /** ☆☆☆ ✔ 3 */
  SharpnessAuto: number
  /** ☆☆☆ ✔ undefined */
  SharpnessFaithful: number
  /** ☆☆☆ ✔ "n/a" */
  SharpnessFrequency: string
  /** ☆☆☆ ✔ 4 */
  SharpnessLandscape: number
  /** ☆☆☆ ✔ 3 */
  SharpnessMonochrome: number
  /** ☆☆☆ ✔ undefined */
  SharpnessNeutral: number
  /** ☆☆☆ ✔ 2 */
  SharpnessPortrait: number
  /** ☆☆☆ ✔ "0 (min -5, max 5)" */
  SharpnessSetting: string
  /** ☆☆☆ ✔ 3 */
  SharpnessStandard: number
  /** ☆☆☆ ✔ 3 */
  SharpnessUserDef1: number
  /** ☆☆☆ ✔ 3 */
  SharpnessUserDef2: number
  /** ☆☆☆ ✔ 3 */
  SharpnessUserDef3: number
  /** ☆☆☆ ✔ "Not Set" */
  ShootingInfoDisplay: string
  /** ☆☆☆ ✔ "10 s" */
  ShootingInfoMonitorOffTime: string
  /** ☆☆☆ ✔ "Enable" */
  ShortReleaseTimeLag: string
  /** ☆☆☆ ✔ "0204" */
  ShotInfoVersion: string
  /** ☆☆☆ ✔ 7 */
  ShotNumberSincePowerUp: number
  /** ☆☆☆ ✔ "AF/AE lock stop" */
  ShutterAELButton: string
  /** ☆☆☆ ✔ "Metering + AF start" */
  ShutterButtonAFOnButton: string
  /** ☆☆☆ ✔ 1137 */
  ShutterCount: number
  /** ☆☆☆ ✔ "1st-curtain sync" */
  ShutterCurtainSync: string
  /** ☆☆☆   "Unknown (20)" */
  ShutterMode: string
  /** ☆☆☆ ✔ "No" */
  ShutterReleaseNoCFCard: string
  /** ☆☆☆ ✔ "Disable" */
  ShutterReleaseWithoutLens: string
  /** ☆☆☆ ✔ "Off" */
  ShutterSpeedLock: string
  /** ☆☆☆ ✔ "Disable; Hi 1/8192; Lo 32" */
  ShutterSpeedRange: string
  /** ☆☆☆ ✔ "Mechanical" */
  ShutterType: string
  /** ☆☆☆   "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" */
  SlaveFlashMeteringSegments: string
  /** ☆☆☆ ✔ "n/a" */
  SlowShutter: string
  /** ☆☆☆ ✔ "Off" */
  SlowSync: string
  /** ☆☆☆   "Blue; 38087" */
  SmartAlbumColor: string
  /** ☆☆☆ ✔ "Off" */
  SoftFocusFilter: string
  /** ☆☆☆ ✔ "Off" */
  SoftSkinEffect: string
  /** ☆☆☆ ✔ {"year":2014,"month":1,"day":10,"hour":8,"minute":3,"second":30,"millis":0} */
  SonyDateTime: ExifDateTime
  /** ☆☆☆ ✔ "1/64" */
  SonyExposureTime: string
  /** ☆☆☆ ✔ 4 */
  SonyFNumber: number
  /** ☆☆☆ ✔ 926 */
  SonyISO: number
  /** ☆☆☆ ✔ 4000 */
  SonyImageHeight: number
  /** ☆☆☆ ✔ 6000 */
  SonyImageWidth: number
  /** ☆☆☆ ✔ "NEX-7" */
  SonyModelID: string
  /** ☆☆☆ ✔ "Normal, Sequence: 0, Panorama: (none)" */
  SpecialMode: string
  /** ☆☆☆ ✔ 15120 */
  SpecularWhiteLevel: number
  /** ☆☆☆ ✔ "Disable (use center AF point)" */
  SpotMeterLinkToAFPoint: string
  /** ☆☆☆ ✔ "Center" */
  SpotMeteringMode: string
  /** ☆☆☆ ✔ "No" */
  StackedImage: string
  /** ☆☆☆ ✔ "6 s" */
  StandbyTimer: string
  /** ☆☆☆ ✔ "Default (from LV)" */
  StartMovieShooting: string
  /** ☆☆☆ ✔ "MIDDLESEX" */
  State: string
  /** ☆☆☆ ✔ 3.2 */
  StopsAboveBaseISO: number
  /** ☆☆☆ ✔ "Off" */
  StoreByOrientation: string
  /** ☆☆☆ ✔ "On" */
  SuperimposedDisplay: string
  /** ☆☆☆ ✔ "Off" */
  SweepPanoramaDirection: string
  /** ☆☆☆ ✔ undefined */
  SweepPanoramaFieldOfView: number
  /** ☆☆☆ ✔ "Disable" */
  SwitchToRegisteredAFPoint: string
  /** ☆☆☆ ✔ 3.2 */
  TargetAperture: number
  /** ☆☆☆ ✔ "1/13" */
  TargetExposureTime: string
  /** ☆☆☆ ✔ "None" */
  Teleconverter: string
  /** ☆☆☆ ✔ "Off" */
  TextStamp: string
  /** ☆☆☆ ✔ "0 159 15 104" */
  ThumbnailImageValidArea: string
  /** ☆☆☆   {"hour":20,"minute":51,"second":10,"millis":0} */
  Time: ExifTime
  /** ☆☆☆   {"hour":17,"minute":35,"second":5,"millis":800} */
  TimeCreated: ExifTime
  /** ☆☆☆ ✔ {"hour":0,"minute":4,"second":47,"millis":50} */
  TimeSincePowerOn: ExifTime
  /** ☆☆☆ ✔ {"year":2007,"month":8,"day":4,"hour":14,"minute":14,"second":42,"millis":0} */
  TimeStamp: ExifDateTime
  /** ☆☆☆ ✔ {"year":2007,"month":7,"day":14,"hour":18,"minute":2,"second":56,"millis":0} */
  TimeStamp1: ExifDateTime
  /** ☆☆☆ ✔ {"tagName":"MakerNotes:TimeZone","input":"+00:00","tzOffsetMinutes":0,"inputWit… */
  TimeZone: ExifTimeZoneOffset
  /** ☆☆☆ ✔ "London" */
  TimeZoneCity: string
  /** ☆☆☆ ✔ "Disable; 6 s: 6; 16 s: 16; After release: 2" */
  TimerLength: string
  /** ☆☆☆ ✔ "Off" */
  TimerRecording: string
  /** ☆☆☆ ✔ undefined */
  Title: string
  /** ☆☆☆ ✔ "Auto" */
  ToneComp: string
  /** ☆☆☆ ✔ "Standard" */
  ToneCurve: string
  /** ☆☆☆ ✔ "Highlights; 0; -7; 7; Shadows; 0; -7; 7; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0… */
  ToneLevel: string
  /** ☆☆☆ ✔ "None" */
  ToningEffect: string
  /** ☆☆☆ ✔ "n/a" */
  ToningEffectAuto: string
  /** ☆☆☆ ✔ "None" */
  ToningEffectMonochrome: string
  /** ☆☆☆ ✔ "None" */
  ToningEffectUserDef1: string
  /** ☆☆☆ ✔ "None" */
  ToningEffectUserDef2: string
  /** ☆☆☆ ✔ "None" */
  ToningEffectUserDef3: string
  /** ☆☆☆ ✔ "n/a" */
  ToningSaturation: string
  /** ☆☆☆   1 */
  TotalZoom: number
  /** ☆☆☆ ✔ "Off" */
  TouchAE: string
  /** ☆☆☆ ✔ "Off" */
  ToyCameraFilter: string
  /** ☆☆☆   "Off" */
  Transform: string
  /** ☆☆☆ ✔ "n/a" */
  TravelDay: string
  /** ☆☆☆ ✔ "Enable after one-shot AF" */
  USMLensElectronicMF: string
  /** ☆☆☆ ✔ "Disable; Flags 0xf0" */
  UsableMeteringModes: string
  /** ☆☆☆ ✔ "Disable; Flags 0xfc" */
  UsableShootingModes: string
  /** ☆☆☆ ✔ "Standard" */
  UserDef1PictureStyle: string
  /** ☆☆☆ ✔ "Standard" */
  UserDef2PictureStyle: string
  /** ☆☆☆ ✔ "Standard" */
  UserDef3PictureStyle: string
  /** ☆☆☆ ✔ "Auto" */
  VFDisplayIllumination: string
  /** ☆☆☆ ✔ undefined */
  VRDOffset: number
  /** ☆☆☆ ✔ "0100" */
  VRInfoVersion: string
  /** ☆☆☆ ✔ "Normal" */
  VRMode: string
  /** ☆☆☆ ✔ 9 */
  ValidAFPoints: number
  /** ☆☆☆ ✔ "12 0" */
  ValidBits: string
  /** ☆☆☆ ✔ "Auto" */
  VariProgram: string
  /** ☆☆☆ ✔ "0130" */
  Version: string
  /** ☆☆☆ ✔ "Same as AF On" */
  VerticalAFOnButton: string
  /** ☆☆☆ ✔ "On" */
  VibrationReduction: string
  /** ☆☆☆ ✔ "Disable" */
  ViewInfoDuringExposure: string
  /** ☆☆☆ ✔ "Exposures Remaining" */
  ViewfinderDisplay: string
  /** ☆☆☆ ✔ "Monochrome, WB corrected, One-touch image quality, [6], [7]" */
  ViewfinderWarnings: string
  /** ☆☆☆ ✔ "Normal" */
  VignetteControl: string
  /** ☆☆☆ ✔ 32 */
  VignettingCorrVersion: number
  /** ☆☆☆ ✔ "Auto" */
  VignettingCorrection: string
  /** ☆☆☆   "Off" */
  VoiceMemo: string
  /** ☆☆☆ ✔ "Off" */
  WBBracketMode: string
  /** ☆☆☆ ✔ undefined */
  WBBracketValueAB: number
  /** ☆☆☆ ✔ undefined */
  WBBracketValueGM: number
  /** ☆☆☆ ✔ "LCD monitor" */
  WBMediaImageSizeSetting: string
  /** ☆☆☆ ✔ 6 */
  WBShiftAB: number
  /** ☆☆☆ ✔ "0 0" */
  WBShiftAB_GM: string
  /** ☆☆☆ ✔ -3 */
  WBShiftGM: number
  /** ☆☆☆ ✔ "256 439 386 256" */
  WB_GRBGLevels: string
  /** ☆☆☆ ✔ "2.078125 1.29296875 1 1" */
  WB_RBLevels: string
  /** ☆☆☆ ✔ "290 692 256 256" */
  WB_RBLevels3000K: string
  /** ☆☆☆ ✔ "354 556 256 256" */
  WB_RBLevels3300K: string
  /** ☆☆☆ ✔ "382 514 256 256" */
  WB_RBLevels3600K: string
  /** ☆☆☆ ✔ "406 482 256 256" */
  WB_RBLevels3900K: string
  /** ☆☆☆ ✔ "486 550 256 256" */
  WB_RBLevels4000K: string
  /** ☆☆☆ ✔ "434 460 256 256" */
  WB_RBLevels4300K: string
  /** ☆☆☆ ✔ "480 468 256 256" */
  WB_RBLevels4500K: string
  /** ☆☆☆ ✔ "470 426 256 256" */
  WB_RBLevels4800K: string
  /** ☆☆☆ ✔ "500 398 256 256" */
  WB_RBLevels5300K: string
  /** ☆☆☆ ✔ "540 364 256 256" */
  WB_RBLevels6000K: string
  /** ☆☆☆ ✔ "572 390 256 256" */
  WB_RBLevels6600K: string
  /** ☆☆☆ ✔ "586 316 256 256" */
  WB_RBLevels7500K: string
  /** ☆☆☆ ✔ "468 414 256 256" */
  WB_RBLevelsCWB1: string
  /** ☆☆☆ ✔ "384 384 256 256" */
  WB_RBLevelsCWB2: string
  /** ☆☆☆ ✔ "384 384 256 256" */
  WB_RBLevelsCWB3: string
  /** ☆☆☆ ✔ "384 384 256 256" */
  WB_RBLevelsCWB4: string
  /** ☆☆☆ ✔ "507 256 428 256" */
  WB_RGBGLevels: string
  /** ☆☆☆ ✔ "547 256 439" */
  WB_RGBLevels: string
  /** ☆☆☆ ✔ "1324 1024 3520" */
  WB_RGBLevels2500K: string
  /** ☆☆☆ ✔ "1720 1024 2496" */
  WB_RGBLevels3200K: string
  /** ☆☆☆ ✔ "2288 1024 1784" */
  WB_RGBLevels4500K: string
  /** ☆☆☆ ✔ "2748 1024 1460" */
  WB_RGBLevels6000K: string
  /** ☆☆☆ ✔ "3256 1024 1228" */
  WB_RGBLevels8500K: string
  /** ☆☆☆ ✔ "2772 1024 1444" */
  WB_RGBLevelsCloudy: string
  /** ☆☆☆ ✔ "2552 1024 1580" */
  WB_RGBLevelsDaylight: string
  /** ☆☆☆ ✔ "2944 1024 1452" */
  WB_RGBLevelsFlash: string
  /** ☆☆☆ ✔ "2356 1024 2272" */
  WB_RGBLevelsFluorescent: string
  /** ☆☆☆ ✔ "1852 1024 2856" */
  WB_RGBLevelsFluorescentM1: string
  /** ☆☆☆ ✔ "2532 1024 1640" */
  WB_RGBLevelsFluorescentP1: string
  /** ☆☆☆ ✔ "2916 1024 1528" */
  WB_RGBLevelsFluorescentP2: string
  /** ☆☆☆ ✔ "3080 1024 1296" */
  WB_RGBLevelsShade: string
  /** ☆☆☆ ✔ "1532 1024 2892" */
  WB_RGBLevelsTungsten: string
  /** ☆☆☆ ✔ "2338 1019 1019 1587" */
  WB_RGGBLevelsAsShot: string
  /** ☆☆☆ ✔ "2338 1023 1023 1587" */
  WB_RGGBLevelsAuto: string
  /** ☆☆☆ ✔ "2639 1023 1023 1353" */
  WB_RGGBLevelsCloudy: string
  /** ☆☆☆ ✔ "128 128 128 128" */
  WB_RGGBLevelsCustom: string
  /** ☆☆☆ ✔ "2425 1023 1023 1492" */
  WB_RGGBLevelsDaylight: string
  /** ☆☆☆ ✔ "2735 1023 1023 1306" */
  WB_RGGBLevelsFlash: string
  /** ☆☆☆ ✔ "2038 1023 1023 1969" */
  WB_RGGBLevelsFluorescent: string
  /** ☆☆☆   "14483 8192 8224 7255" */
  WB_RGGBLevelsFluorescentD: string
  /** ☆☆☆   "11995 8192 8224 8090" */
  WB_RGGBLevelsFluorescentN: string
  /** ☆☆☆   "10660 8192 8224 9843" */
  WB_RGGBLevelsFluorescentW: string
  /** ☆☆☆ ✔ "2185 1024 1024 1535" */
  WB_RGGBLevelsKelvin: string
  /** ☆☆☆ ✔ "1912 1028 1019 1791" */
  WB_RGGBLevelsMeasured: string
  /** ☆☆☆ ✔ "8191 1024 1024 8191" */
  WB_RGGBLevelsPC1: string
  /** ☆☆☆ ✔ "8191 1024 1024 8191" */
  WB_RGGBLevelsPC2: string
  /** ☆☆☆ ✔ "8191 1024 1024 8191" */
  WB_RGGBLevelsPC3: string
  /** ☆☆☆ ✔ "2847 1023 1023 1249" */
  WB_RGGBLevelsShade: string
  /** ☆☆☆ ✔ "1597 1023 1023 2302" */
  WB_RGGBLevelsTungsten: string
  /** ☆☆☆ ✔ "Off" */
  WatercolorFilter: string
  /** ☆☆☆ ✔ "Auto" */
  WhiteBalance2: string
  /** ☆☆☆   "356 807" */
  WhiteBalanceBias: number
  /** ☆☆☆ ✔ -1 */
  WhiteBalanceBlue: number
  /** ☆☆☆ ✔ "0 0" */
  WhiteBalanceBracket: string
  /** ☆☆☆ ✔ "Red +0, Blue +0" */
  WhiteBalanceFineTune: number
  /** ☆☆☆   "Auto (Tungsten)" */
  WhiteBalanceMode: string
  /** ☆☆☆ ✔ -1 */
  WhiteBalanceRed: number
  /** ☆☆☆ ✔ "Auto" */
  WhiteBalanceTemperature: string
  /** ☆☆☆   "9296 13510" */
  WhiteBoard: number
  /** ☆☆☆ ✔ "15360 15360 15360" */
  WhiteLevel: string
  /** ☆☆☆   "Off" */
  WideRange: string
  /** ☆☆☆ ✔ "Hometown" */
  WorldTimeLocation: string
  /** ☆☆☆ ✔ 12770.8 */
  YawAngle: number
  /** ☆☆☆   2005 */
  YearCreated: number
  /** ☆☆☆ ✔ "ISO Setting Used" */
  ZoneMatching: string
  /** ☆☆☆ ✔ 1920 */
  ZoomSourceWidth: number
  /** ☆☆☆ ✔ 31 */
  ZoomStepCount: number
  /** ☆☆☆ ✔ 1920 */
  ZoomTargetWidth: number
}

export interface PrintIMTags {
  /** ★☆☆ ✔ "0300" */
  PrintIMVersion: string
}

export interface JFIFTags {
  /** ★☆☆ ✔ 1.01 */
  JFIFVersion: number
}

export interface XMPTags {
  /** ☆☆☆ ✔ "uuid:99e3a6d2-ab71-11d8-a734-f5ed6cd01ff9" */
  About: string
  /** ☆☆☆ ✔ ["Subjekt|Natur|Pflanzen","Ort|Deutschland|Rangsdorf"] */
  CatalogSets: string[]
  /** ☆☆☆ ✔ "Photos 1.0.1" */
  CreatorTool: string
  /** ☆☆☆ ✔ {"year":2014,"month":5,"day":11,"hour":13,"minute":8,"second":25,"millis":659} */
  DateAcquired: ExifDateTime
  /** ☆☆☆ ✔ {"year":2015,"month":6,"day":2,"hour":9,"minute":56,"second":1,"millis":0} */
  DateTime: ExifDateTime
  /** ☆☆☆ ✔ {"year":2015,"month":6,"day":2,"hour":9,"minute":56,"second":1,"tzoffsetMinutes… */
  DateUTC: ExifDateTime
  /** ☆☆☆ ✔ "Castle Rock" */
  Description: string
  /** ☆☆☆ ✔ "adobe:docid:photoshop:99e3a6d0-ab71-11d8-a734-f5ed6cd01ff9" */
  DocumentID: string
  /** ☆☆☆ ✔ "image/jpeg" */
  Format: string
  /** ☆☆☆ ✔ "点像F11" */
  HierarchicalSubject: string
  /** ☆☆☆ ✔ ["saved","saved"] */
  HistoryAction: string[]
  /** ☆☆☆ ✔ ["/metadata","/metadata"] */
  HistoryChanged: string[]
  /** ☆☆☆ ✔ ["xmp.iid:4d4cb5c0-5d51-4cc0-a638-bc5a6cf3f44f","xmp.iid:195a0cd4-8115-4cb9-89e… */
  HistoryInstanceID: string[]
  /** ☆☆☆ ✔ ["Adobe Photoshop Camera Raw 8.6","Adobe Photoshop Camera Raw 8.6 (Macintosh)"] */
  HistorySoftwareAgent: string[]
  /** ☆☆☆ ✔ ["2014:11:11 15:27:28Z","2014:11:11 15:27:29Z"] */
  HistoryWhen: string[]
  /** ☆☆☆ ✔ 1425 */
  ImageNumber: number
  /** ☆☆☆ ✔ "xmp.iid:195a0cd4-8115-4cb9-89e4-fe6d8b9319fd" */
  InstanceID: string
  /** ☆☆☆ ✔ "Picture" */
  LastKeywordXMP: string
  /** ☆☆☆ ✔ {"year":2014,"month":11,"day":11,"hour":15,"minute":27,"second":29,"tzoffsetMin… */
  MetadataDate: ExifDateTime
  /** ☆☆☆ ✔ {"year":2015,"month":6,"day":2,"hour":9,"minute":56,"second":1,"millis":0} */
  ModificationDate: ExifDateTime
  /** ☆☆☆ ✔ "D2A319020F9FD0935CABCB60F534E0E0" */
  OriginalDocumentID: string
  /** ☆☆☆ ✔ 32 */
  PhotographicSensitivity: number
  /** ☆☆☆   undefined */
  RatingPercent: number
  /** ☆☆☆ ✔ "DSCF0722.JPG" */
  RawFileName: string
  /** ☆☆☆ ✔ 2448 */
  RegionAppliedToDimensionsH: number
  /** ☆☆☆ ✔ "pixel" */
  RegionAppliedToDimensionsUnit: string
  /** ☆☆☆ ✔ 3264 */
  RegionAppliedToDimensionsW: number
  /** ☆☆☆ ✔ 0.491 */
  RegionAreaH: number
  /** ☆☆☆ ✔ "normalized" */
  RegionAreaUnit: string
  /** ☆☆☆ ✔ 0.369 */
  RegionAreaW: number
  /** ☆☆☆ ✔ 0.578 */
  RegionAreaX: number
  /** ☆☆☆ ✔ 0.458 */
  RegionAreaY: number
  /** ☆☆☆ ✔ 180 */
  RegionExtensionsAngleInfoRoll: number
  /** ☆☆☆ ✔ 293 */
  RegionExtensionsConfidenceLevel: number
  /** ☆☆☆ ✔ 6 */
  RegionExtensionsFaceID: number
  /** ☆☆☆ ✔ -1179414036 */
  RegionExtensionsTimeStamp: number
  /** ☆☆☆ ✔ "Face" */
  RegionType: string
  /** ☆☆☆ ✔ "Picture" */
  Subject: string
  /** ☆☆☆ ✔ ["Subjekt/Natur/Pflanzen","Ort/Deutschland/Rangsdorf"] */
  TagsList: string[]
  /** ☆☆☆ ✔ "0 (reserved)" */
  Urgency: string
  /** ☆☆☆ ✔ "XMP toolkit 2.8.2-33, framework 1.5" */
  XMPToolkit: string
}

export interface PhotoshopTags {
  /** ☆☆☆ ✔ "00000000000000000000000000000000" */
  IPTCDigest: string
}

export interface FlashPixTags {
  /** ☆☆☆   "Unicode UTF-16, little endian" */
  CodePage: string
  /** ☆☆☆   "Picoss" */
  CreatingApplication: string
  /** ☆☆☆   "30020010-C06F-D011-BD01-00609719A180" */
  ExtensionClassID: string
  /** ☆☆☆   {"year":2003,"month":3,"day":29,"hour":17,"minute":47,"second":50,"millis":0} */
  ExtensionCreateDate: ExifDateTime
  /** ☆☆☆   "Presized image for LCD display" */
  ExtensionDescription: string
  /** ☆☆☆   {"year":2003,"month":3,"day":29,"hour":17,"minute":47,"second":50,"millis":0} */
  ExtensionModifyDate: ExifDateTime
  /** ☆☆☆   "Screen Nail" */
  ExtensionName: string
  /** ☆☆☆   "Invalidated By Modification" */
  ExtensionPersistence: string
  /** ☆☆☆ ✔ 480 */
  PreviewImageHeight: number
  /** ☆☆☆ ✔ 640 */
  PreviewImageWidth: number
  /** ☆☆☆   "(Binary data 14629 bytes, use -b option to extract)" */
  ScreenNail: string
  /** ☆☆☆   1 */
  UsedExtensionNumbers: number
}

export interface ICC_ProfileTags {
  /** ☆☆☆ ✔ "0.14307 0.06061 0.7141" */
  BlueMatrixColumn: string
  /** ☆☆☆ ✔ "(Binary data 2060 bytes, use -b option to extract)" */
  BlueTRC: string
  /** ☆☆☆ ✔ "Not Embedded, Independent" */
  CMMFlags: string
  /** ☆☆☆ ✔ "1.04788 0.02292 -0.0502 0.02959 0.99048 -0.01706 -0.00923 0.01508 0.75168" */
  ChromaticAdaptation: string
  /** ☆☆☆ ✔ "RGB " */
  ColorSpaceData: string
  /** ☆☆☆ ✔ "0.9642 1 0.82491" */
  ConnectionSpaceIlluminant: string
  /** ☆☆☆ ✔ "Reflective, Glossy, Positive, Color" */
  DeviceAttributes: string
  /** ☆☆☆ ✔ "IEC " */
  DeviceManufacturer: string
  /** ☆☆☆ ✔ "IEC http://www.iec.ch" */
  DeviceMfgDesc: string
  /** ☆☆☆ ✔ "sRGB" */
  DeviceModel: string
  /** ☆☆☆ ✔ "IEC 61966-2.1 Default RGB colour space - sRGB" */
  DeviceModelDesc: string
  /** ☆☆☆ ✔ "0.38515 0.71687 0.09708" */
  GreenMatrixColumn: string
  /** ☆☆☆ ✔ "(Binary data 2060 bytes, use -b option to extract)" */
  GreenTRC: string
  /** ☆☆☆ ✔ "76.03647 80 87.12462" */
  Luminance: string
  /** ☆☆☆ ✔ "0 0 0" */
  MeasurementBacking: string
  /** ☆☆☆ ✔ "0.999%" */
  MeasurementFlare: string
  /** ☆☆☆ ✔ "Unknown" */
  MeasurementGeometry: string
  /** ☆☆☆ ✔ "D65" */
  MeasurementIlluminant: string
  /** ☆☆☆ ✔ "CIE 1931" */
  MeasurementObserver: string
  /** ☆☆☆ ✔ "0 0 0" */
  MediaBlackPoint: string
  /** ☆☆☆ ✔ "0.95045 1 1.08905" */
  MediaWhitePoint: string
  /** ☆☆☆ ✔ "Microsoft Corporation" */
  PrimaryPlatform: string
  /** ☆☆☆ ✔ "Lino" */
  ProfileCMMType: string
  /** ☆☆☆ ✔ "Display Device Profile" */
  ProfileClass: string
  /** ☆☆☆ ✔ "XYZ " */
  ProfileConnectionSpace: string
  /** ☆☆☆ ✔ "Copyright (c) 1998 Hewlett-Packard Company" */
  ProfileCopyright: string
  /** ☆☆☆ ✔ "HP  " */
  ProfileCreator: string
  /** ☆☆☆ ✔ {"year":1998,"month":2,"day":9,"hour":6,"minute":49,"second":0,"millis":0} */
  ProfileDateTime: ExifDateTime
  /** ☆☆☆ ✔ "sRGB IEC61966-2.1" */
  ProfileDescription: string
  /** ☆☆☆   "Camera RGB Profile" */
  ProfileDescriptionML: string
  /** ☆☆☆ ✔ "acsp" */
  ProfileFileSignature: string
  /** ☆☆☆ ✔ "e5bb0e9867bd46cd4bbe446ebd1b7598" */
  ProfileID: number
  /** ☆☆☆ ✔ "2.1.0" */
  ProfileVersion: string
  /** ☆☆☆ ✔ "0.43607 0.22249 0.01392" */
  RedMatrixColumn: string
  /** ☆☆☆ ✔ "(Binary data 2060 bytes, use -b option to extract)" */
  RedTRC: string
  /** ☆☆☆ ✔ "Perceptual" */
  RenderingIntent: string
  /** ☆☆☆ ✔ "Cathode Ray Tube Display" */
  Technology: string
  /** ☆☆☆ ✔ "Reference Viewing Condition in IEC61966-2.1" */
  ViewingCondDesc: string
  /** ☆☆☆ ✔ "19.6445 20.3718 16.8089" */
  ViewingCondIlluminant: string
  /** ☆☆☆ ✔ "D50" */
  ViewingCondIlluminantType: string
  /** ☆☆☆ ✔ "3.92889 4.07439 3.36179" */
  ViewingCondSurround: string
}

export interface IPTCTags {
  /** ☆☆☆ ✔ 4 */
  ApplicationRecordVersion: number
  /** ☆☆☆ ✔ "UTF8" */
  CodedCharacterSet: string
  /** ☆☆☆ ✔ {"year":2016,"month":8,"day":12} */
  DigitalCreationDate: ExifDate
  /** ☆☆☆ ✔ {"hour":13,"minute":28,"second":50,"millis":0} */
  DigitalCreationTime: ExifTime
  /** ☆☆☆ ✔ 2 */
  EnvelopeRecordVersion: number
  /** ☆☆☆ ✔ "点像F11" */
  Keywords: string
  /** ☆☆☆ ✔ "Microsoft Windows Photo Viewer 6.1.7600.16385" */
  OriginatingProgram: string
  /** ☆☆☆ ✔ "4.13.0" */
  ProgramVersion: string
}

export interface MPFTags {
  /** ☆☆☆ ✔ 640 */
  DependentImage1EntryNumber: number
  /** ☆☆☆ ✔ 424 */
  DependentImage2EntryNumber: number
  /** ☆☆☆   "(Binary data 66 bytes, use -b option to extract)" */
  ImageUIDList: string
  /** ☆☆☆ ✔ "0100" */
  MPFVersion: string
  /** ☆☆☆ ✔ "(Binary data 900042 bytes, use -b option to extract)" */
  MPImage3: string
  /** ☆☆☆ ✔ "Dependent child image" */
  MPImageFlags: string
  /** ☆☆☆ ✔ "JPEG" */
  MPImageFormat: string
  /** ☆☆☆ ✔ 636948 */
  MPImageLength: number
  /** ☆☆☆ ✔ 5677596 */
  MPImageStart: number
  /** ☆☆☆ ✔ "Large Thumbnail (full HD equivalent)" */
  MPImageType: string
  /** ☆☆☆ ✔ 2 */
  NumberOfImages: number
  /** ☆☆☆   1 */
  TotalFrames: number
}

export interface APP1Tags {
  /** ☆☆☆   "59 128 128" */
  AboveColor: string
  /** ☆☆☆   "19.5 C" */
  AtmosphericTemperature: string
  /** ☆☆☆   0.006569 */
  AtmosphericTransAlpha1: number
  /** ☆☆☆   0.01262 */
  AtmosphericTransAlpha2: number
  /** ☆☆☆   -0.002276 */
  AtmosphericTransBeta1: number
  /** ☆☆☆   -0.00667 */
  AtmosphericTransBeta2: number
  /** ☆☆☆   1.9 */
  AtmosphericTransX: number
  /** ☆☆☆   "169 128 128" */
  BelowColor: string
  /** ☆☆☆   "B20 HS PAL" */
  CameraModel: string
  /** ☆☆☆   "2532832218DE" */
  CameraPartNumber: string
  /** ☆☆☆   25301183 */
  CameraSerialNumber: number
  /** ☆☆☆   "2.4.12" */
  CameraSoftware: string
  /** ☆☆☆   "135.0 C" */
  CameraTemperatureMaxClip: string
  /** ☆☆☆   "150.0 C" */
  CameraTemperatureMaxSaturated: string
  /** ☆☆☆   "120.0 C" */
  CameraTemperatureMaxWarn: string
  /** ☆☆☆   "-45.0 C" */
  CameraTemperatureMinClip: string
  /** ☆☆☆   "-273.0 C" */
  CameraTemperatureMinSaturated: string
  /** ☆☆☆   "-40.0 C" */
  CameraTemperatureMinWarn: string
  /** ☆☆☆   "120.0 C" */
  CameraTemperatureRangeMax: string
  /** ☆☆☆   "-40.0 C" */
  CameraTemperatureRangeMin: string
  /** ☆☆☆   "MTX IR" */
  CreatorSoftware: string
  /** ☆☆☆   "23.4 deg" */
  FieldOfView: string
  /** ☆☆☆   "NOF" */
  FilterModel: string
  /** ☆☆☆   undefined */
  FilterPartNumber: string
  /** ☆☆☆   "00000000" */
  FilterSerialNumber: string
  /** ☆☆☆   "20.0 C" */
  IRWindowTemperature: string
  /** ☆☆☆   1 */
  IRWindowTransmission: number
  /** ☆☆☆   "99 128 128" */
  Isotherm1Color: string
  /** ☆☆☆   "145 35 53" */
  Isotherm2Color: string
  /** ☆☆☆   "0000000" */
  LensPartNumber: string
  /** ☆☆☆   "1.00 m" */
  ObjectDistance: string
  /** ☆☆☆   "67 215 98" */
  OverflowColor: string
  /** ☆☆☆   "(Binary data 672 bytes, use -b option to extract)" */
  Palette: string
  /** ☆☆☆   224 */
  PaletteColors: number
  /** ☆☆☆   "28.0/system/rainHC.pal" */
  PaletteFileName: string
  /** ☆☆☆   undefined */
  PaletteMethod: number
  /** ☆☆☆   "Rainbow HC" */
  PaletteName: string
  /** ☆☆☆   1 */
  PaletteStretch: number
  /** ☆☆☆   1388.1 */
  PlanckB: number
  /** ☆☆☆   1 */
  PlanckF: number
  /** ☆☆☆   -4096 */
  PlanckO: number
  /** ☆☆☆   14494.547 */
  PlanckR1: number
  /** ☆☆☆   0.016238369 */
  PlanckR2: number
  /** ☆☆☆   "(Binary data 77606 bytes, use -b option to extract)" */
  RawThermalImage: string
  /** ☆☆☆   240 */
  RawThermalImageHeight: number
  /** ☆☆☆   "PNG" */
  RawThermalImageType: string
  /** ☆☆☆   320 */
  RawThermalImageWidth: number
  /** ☆☆☆   13182 */
  RawValueMedian: number
  /** ☆☆☆   1696 */
  RawValueRange: number
  /** ☆☆☆   "19.5 C" */
  ReflectedApparentTemperature: string
  /** ☆☆☆   "57.0 %" */
  RelativeHumidity: string
  /** ☆☆☆   "40 109 239" */
  UnderflowColor: string
}

export interface APP4Tags {
  /** ☆☆☆   85 */
  PreviewQuality: number
}

export interface RAFTags {
  /** ☆☆☆ ✔ "294.2 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 6.8e-05 0.000124 0.000152 0.000142… */
  ChromaticAberrationParams: string
  /** ☆☆☆ ✔ "10 11 9 8" */
  FujiLayout: string
  /** ☆☆☆ ✔ "267.4545455 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 0 -0.172 -0.483 -1.068 -2.… */
  GeometricDistortionParams: string
  /** ☆☆☆ ✔ -0.7 */
  RawExposureBias: number
  /** ☆☆☆ ✔ 3288 */
  RawImageFullHeight: number
  /** ☆☆☆ ✔ "5120x3288" */
  RawImageFullSize: string
  /** ☆☆☆ ✔ 5120 */
  RawImageFullWidth: number
  /** ☆☆☆ ✔ "267.4545455 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 100 97.47 94.65 91.21 86.8… */
  VignettingParams: string
  /** ☆☆☆ ✔ "302 551 531" */
  WB_GRBLevels: string
  /** ☆☆☆ ✔ "302 549 531" */
  WB_GRBLevelsAuto: string
  /** ☆☆☆ ✔ "302 351 865 17 302 645 459 21" */
  WB_GRBLevelsStandard: string
  /** ☆☆☆ ✔ "BGGRGG RGGBGG GBRGRB RGGBGG BGGRGG GRBGBR" */
  XTransLayout: string
}

export interface PanasonicRawTags {
  /** ☆☆☆ ✔ 0.015594482421875 */
  DistortionParam02: number
  /** ☆☆☆ ✔ 0.005401611328125 */
  DistortionParam04: number
  /** ☆☆☆ ✔ 0.094757080078125 */
  DistortionParam08: number
  /** ☆☆☆ ✔ 0.019195556640625 */
  DistortionParam09: number
  /** ☆☆☆ ✔ -0.00054931640625 */
  DistortionParam11: number
  /** ☆☆☆ ✔ 1 */
  DistortionScale: number
  /** ☆☆☆ ✔ 7 */
  NumWBEntries: number
  /** ☆☆☆ ✔ "Fine Weather" */
  WBType1: string
  /** ☆☆☆ ✔ "Cloudy" */
  WBType2: string
  /** ☆☆☆ ✔ "Shade" */
  WBType3: string
  /** ☆☆☆ ✔ "Tungsten (Incandescent)" */
  WBType4: string
  /** ☆☆☆ ✔ "Flash" */
  WBType5: string
  /** ☆☆☆ ✔ "D55" */
  WBType6: string
  /** ☆☆☆ ✔ "ISO Studio Tungsten" */
  WBType7: string
  /** ☆☆☆ ✔ "633 256 415" */
  WB_RGBLevels1: string
  /** ☆☆☆ ✔ "665 256 389" */
  WB_RGBLevels2: string
  /** ☆☆☆ ✔ "717 256 367" */
  WB_RGBLevels3: string
  /** ☆☆☆ ✔ "439 256 597" */
  WB_RGBLevels4: string
  /** ☆☆☆ ✔ "650 256 382" */
  WB_RGBLevels5: string
  /** ☆☆☆ ✔ "592 256 413" */
  WB_RGBLevels6: string
  /** ☆☆☆ ✔ "439 256 597" */
  WB_RGBLevels7: string
}

export interface Tags extends
  ExifToolTags,
  FileTags,
  EXIFTags,
  CompositeTags,
  MakerNotesTags,
  PrintIMTags,
  JFIFTags,
  XMPTags,
  PhotoshopTags,
  FlashPixTags,
  ICC_ProfileTags,
  IPTCTags,
  MPFTags,
  APP1Tags,
  APP4Tags,
  RAFTags,
  PanasonicRawTags {
  errors: string[]
  /** "Unknown file type" */
  Error: string
  SourceFile: string
}
